<a href="https://colab.research.google.com/github/merve-kasap/data-science-essentials-5/blob/main/ZMa1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

After talking to Zhenzhong, I got the excel files that storm generated. Here, the goal is to make a master file from each experimental point. 
From a single excel file, we are interested in extracting the **count** , and **mean** parameters as a single point.

We first upload pandas and numpy modules in order to excel like analysis in python.

In [53]:
import pandas as pd

In [54]:
import numpy as np

In [55]:
from scipy import stats

We read the file in:

In [56]:
B_K_1 = pd.read_csv('/content/B+K 040822_ZMA010 SLICE1A-0.71.csv')

In order to check whether we succesfully uploaded the excel file, we check the first 5 rows from this file:

In [57]:
B_K_1.head()

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.356863,0.925490,0.231373,0.001442,-1,0.075306,-1,...,-176.9020,-1,69.3237,55.3218,35.1483,4999,161,0,0,NaN
1,2,1,0,0.850980,0.188235,0.941176,0.021511,-1,0.540057,-1,...,-313.8700,-1,216.9920,142.2270,97.3481,2040,21,0,0,NaN
2,3,1,0,0.164706,0.031372,0.137255,0.001781,-1,0.081712,-1,...,695.5460,-1,71.6686,59.5592,46.6156,1252,147,0,0,NaN
3,4,1,0,0.043137,0.105882,0.760784,0.009755,-1,0.310439,-1,...,77.6952,-1,136.9830,98.5647,68.9434,991,0,0,0,NaN
4,5,1,0,0.141176,0.874510,0.901961,0.009597,-1,0.340488,-1,...,-359.2960,-1,163.6880,99.3785,65.2845,878,0,0,0,NaN

We then check the column names in order to see which ones we are interested in:

In [58]:
B_K_1.columns

Index(['id', ' visible', ' probe', ' colorR', ' colorG', ' colorB',
       ' volumeAlpha', ' volumeIso', ' surfaceAreaAlpha', ' surfaceAreaIso',
       ' sphericityAlpha', ' sphericityIso', ' radiusOfGyration',
       ' particleCount', ' densityAlpha', ' densityIso', ' centroidX',
       ' centroidY', ' centroidZ', ' distance', ' PCA1', ' PCA2', ' PCA3',
       ' probeParticleCountAlpha1', ' probeParticleCountAlpha2',
       ' probeParticleCountIso1', ' probeParticleCountIso2', 'notes'],
      dtype='object')

We are not interested in ' visible', ' colorR', ' colorG', ' colorB', 'notes' columns. So we drop them:

In [59]:
B_K_1.drop([' visible', ' colorR', ' colorG', ' colorB', 'notes'], axis='columns', inplace=True)

Once again we check to see whether we got rid of the columns:

In [60]:
B_K_1.columns

Index(['id', ' probe', ' volumeAlpha', ' volumeIso', ' surfaceAreaAlpha',
       ' surfaceAreaIso', ' sphericityAlpha', ' sphericityIso',
       ' radiusOfGyration', ' particleCount', ' densityAlpha', ' densityIso',
       ' centroidX', ' centroidY', ' centroidZ', ' distance', ' PCA1', ' PCA2',
       ' PCA3', ' probeParticleCountAlpha1', ' probeParticleCountAlpha2',
       ' probeParticleCountIso1', ' probeParticleCountIso2'],
      dtype='object')

One important note here, pandas do not like empty rows, so we check to see if there are any missing values in any of columns:

In [61]:
B_K_1.isnull().sum()

id                           0
 probe                       0
 volumeAlpha                 0
 volumeIso                   0
 surfaceAreaAlpha            0
 surfaceAreaIso              0
 sphericityAlpha             0
 sphericityIso               0
 radiusOfGyration            0
 particleCount               0
 densityAlpha                0
 densityIso                  0
 centroidX                   0
 centroidY                   0
 centroidZ                   0
 distance                    0
 PCA1                        0
 PCA2                        0
 PCA3                        0
 probeParticleCountAlpha1    0
 probeParticleCountAlpha2    0
 probeParticleCountIso1      0
 probeParticleCountIso2      0
dtype: int64

Now that we confirmed that each row has values, we get the descriptive statistics for the columns:

In [62]:
B_K_1.describe()

,id,probe,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,sphericityAlpha,sphericityIso,radiusOfGyration,particleCount,...,centroidY,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2
count,2123.000000,2123.000000,2123.000000,2123.0,2123.000000,2123.0,2123.000000,2123.0,2123.000000,2123.000000,...,2123.000000,2123.000000,2123.0,2123.000000,2123.000000,2123.000000,2123.000000,2123.000000,2123.0,2123.0
mean,1062.000000,0.270372,0.001776,-1.0,0.092239,-1.0,0.718549,-1.0,74.526102,67.567122,...,25559.844248,-79.650100,-1.0,138.711528,108.828666,62.450592,44.088554,23.909091,0.0,0.0
std,613.001631,0.444257,0.001563,0.0,0.050410,0.0,0.077812,0.0,16.816251,190.632230,...,14669.550774,303.557012,0.0,34.548661,26.929720,19.493489,127.600644,148.780521,0.0,0.0
min,1.000000,0.000000,0.000070,-1.0,0.013540,-1.0,0.428173,-1.0,30.585800,23.000000,...,780.500000,-699.990000,-1.0,54.212300,39.572500,14.737700,0.000000,0.000000,0.0,0.0
25%,531.500000,0.000000,0.000794,-1.0,0.057571,-1.0,0.668941,-1.0,64.146550,37.000000,...,11564.450000,-339.426500,-1.0,117.822000,90.133950,47.624800,1.000000,0.000000,0.0,0.0
50%,1062.000000,0.000000,0.001311,-1.0,0.079409,-1.0,0.725346,-1.0,73.463100,47.000000,...,26915.000000,-141.992000,-1.0,134.390000,109.325000,62.359600,38.000000,0.000000,0.0,0.0
75%,1592.500000,1.000000,0.002259,-1.0,0.114289,-1.0,0.775158,-1.0,83.958150,65.000000,...,38754.900000,133.847500,-1.0,154.603500,127.110500,76.291550,53.000000,32.000000,0.0,0.0
max,2123.000000,1.000000,0.021511,-1.0,0.540057,-1.0,0.901709,-1.0,166.417000,5001.000000,...,49848.800000,706.960000,-1.0,383.173000,209.485000,130.264000,4999.000000,5001.000000,0.0,0.0

# Appending all files

Now, first let's merge all the files together:

In [63]:
import os

In [64]:
# assign path
path, dirs, files = next(os.walk("/content/"))
file_count = len(files)
# create empty list
dataframes_list = []

In [65]:
# append datasets to the list
for i in range(file_count):
    temp_df = pd.read_csv("/content/" + files[i])
    dataframes_list.append(temp_df)
     
# display datasets
for dataset in dataframes_list:
    display(dataset)

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.298039,0.870588,0.698039,0.013966,-1,0.355356,-1,...,-139.4270,-1,115.7900,95.3415,72.5402,4893,1785,0,0,NaN
1,2,1,0,0.509804,0.996078,0.043137,0.001977,-1,0.093571,-1,...,45.5828,-1,71.8508,68.7831,35.1354,4781,638,0,0,NaN
2,3,1,0,0.000000,0.905882,0.196078,0.038442,-1,0.913335,-1,...,177.5850,-1,365.5630,137.6920,83.7825,3699,315,0,0,NaN
3,4,1,0,0.482353,0.847059,0.631373,0.018087,-1,0.486205,-1,...,-141.0020,-1,193.0190,134.3800,82.5904,847,1,0,0,NaN
4,5,1,0,0.023529,0.870588,0.419608,0.005072,-1,0.208817,-1,...,-39.9587,-1,127.4540,88.2611,57.0123,520,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3636,3637,1,1,0.647059,0.333333,0.552941,0.001093,-1,0.063319,-1,...,-264.5020,-1,122.7360,108.8090,75.7376,0,30,0,0,NaN
3637,3638,1,1,0.600000,0.929412,0.203922,0.000146,-1,0.025714,-1,...,-353.3460,-1,100.6960,49.0307,20.2748,0,30,0,0,NaN
3638,3639,1,1,0.015686,0.521569,0.470588,0.000151,-1,0.018974,-1,...,-100.5640,-1,79.4942,46.9068,29.4518,0,30,0,0,NaN
3639,3640,1,1,0.698039,0.050980,0.960784,0.000679,-1,0.047305,-1,...,663.2690,-1,118.2710,100.0240,48.7855,0,30,0,0,NaN
3640,3641,1,1,0.239216,0.768627,0.745098,0.000428,-1,0.039112,-1,...,-345.1000,-1,96.4802,85.1060,34.9643,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.301961,0.200000,0.058824,0.009905,-1,0.296694,-1,...,37.6046,-1,106.5870,97.0763,65.7333,4875,1487,0,0,NaN
1,2,1,0,0.486275,0.207843,0.925490,0.009837,-1,0.314940,-1,...,-67.3475,-1,119.0800,96.9463,53.7354,3823,647,0,0,NaN
2,3,1,0,0.349020,0.964706,0.639216,0.000945,-1,0.071883,-1,...,-330.2990,-1,57.7864,48.7821,26.5060,1841,223,0,0,NaN
3,4,1,0,0.458824,0.360784,0.956863,0.019101,-1,0.456662,-1,...,-281.4320,-1,147.9990,127.3570,100.0790,1521,168,0,0,NaN
4,5,1,0,0.435294,0.835294,0.666667,0.012767,-1,0.406620,-1,...,-15.4884,-1,279.1980,148.4320,71.8862,381,79,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3684,3685,1,1,0.223529,0.850980,0.329412,0.000930,-1,0.056384,-1,...,644.1200,-1,111.9550,102.9520,63.2042,0,30,0,0,NaN
3685,3686,1,1,0.407843,0.854902,0.043137,0.000292,-1,0.031489,-1,...,-472.0020,-1,123.7190,63.4740,29.8290,0,30,0,0,NaN
3686,3687,1,1,0.423529,0.423529,0.776471,0.000299,-1,0.028348,-1,...,-202.2750,-1,117.3180,72.7882,48.0006,0,30,0,0,NaN
3687,3688,1,1,0.874510,0.819608,0.654902,0.000742,-1,0.051971,-1,...,-22.0016,-1,95.5429,94.5298,56.8771,0,30,0,0,NaN
3688,3689,1,1,0.976471,0.486275,0.231373,0.000322,-1,0.039356,-1,...,244.3340,-1,102.3300,79.4676,29.9017,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.768627,0.098039,0.549020,0.040415,-1,0.984887,-1,...,161.5660,-1,513.8190,201.7940,96.1735,3379,310,0,0,NaN
1,2,1,0,0.313725,0.321569,0.019608,0.018645,-1,0.549407,-1,...,-376.1660,-1,319.7730,130.9500,69.2059,2445,110,0,0,NaN
2,3,1,0,0.450980,0.894118,0.858824,0.007606,-1,0.284379,-1,...,517.3280,-1,229.8620,95.5157,59.8040,1102,0,0,0,NaN
3,4,1,0,0.384314,0.968627,0.807843,0.001945,-1,0.101296,-1,...,-143.0130,-1,89.2922,65.1651,44.4503,430,0,0,0,NaN
4,5,1,0,0.160784,0.925490,0.388235,0.003329,-1,0.192893,-1,...,-412.1710,-1,178.9380,79.9275,48.5766,371,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4427,4428,1,1,0.105882,0.133333,0.172549,0.000265,-1,0.031450,-1,...,-85.2237,-1,93.8923,63.5950,30.3628,0,30,0,0,NaN
4428,4429,1,1,0.996078,0.980392,0.619608,0.000312,-1,0.036374,-1,...,-73.8863,-1,89.5567,70.7707,35.3762,0,30,0,0,NaN
4429,4430,1,1,0.650980,0.356863,0.584314,0.000440,-1,0.038612,-1,...,-55.6909,-1,76.8139,73.5356,37.9324,6,30,0,0,NaN
4430,4431,1,1,0.372549,0.776471,0.792157,0.000285,-1,0.027151,-1,...,-695.8060,-1,90.3143,90.1017,38.6864,0,30,0,0,NaN
4431,4432,1,1,0.231373,0.482353,0.662745,0.000110,-1,0.017149,-1,...,58.0624,-1,77.7522,46.5514,24.4116,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.352941,0.192157,0.643137,0.013098,-1,0.328136,-1,...,-46.1514,-1,126.9230,116.1330,79.3773,3027,157,0,0,NaN
1,2,1,0,0.654902,0.435294,0.631373,0.007228,-1,0.266078,-1,...,-234.7500,-1,139.8240,85.1541,55.1305,1178,0,0,0,NaN
2,3,1,0,0.156863,0.121569,0.498039,0.004358,-1,0.221475,-1,...,14.5505,-1,246.6830,65.1278,43.6473,818,0,0,0,NaN
3,4,1,0,0.815686,0.694118,0.215686,0.008617,-1,0.299907,-1,...,-130.9630,-1,174.6420,105.8100,70.5244,678,0,0,0,NaN
4,5,1,0,0.780392,0.698039,0.733333,0.014324,-1,0.464610,-1,...,237.4940,-1,388.0020,117.8530,72.5869,602,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4274,4275,1,1,0.623529,0.670588,0.223529,0.000224,-1,0.024982,-1,...,324.5830,-1,134.1340,58.9151,29.1004,0,30,0,0,NaN
4275,4276,1,1,0.878431,0.078431,0.086275,0.000234,-1,0.032404,-1,...,472.6350,-1,120.4610,81.8881,30.2126,0,30,0,0,NaN
4276,4277,1,1,0.717647,0.160784,0.627451,0.000064,-1,0.012918,-1,...,-385.4630,-1,90.5929,32.4495,20.1845,0,30,0,0,NaN
4277,4278,1,1,0.243137,0.203922,0.152941,0.000176,-1,0.020161,-1,...,116.0060,-1,68.4567,54.0650,31.4624,0,30,0,0,NaN
4278,4279,1,1,0.796078,0.262745,0.317647,0.000641,-1,0.048881,-1,...,-290.3700,-1,107.1090,95.4883,53.1987,0,27,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.670588,0.325490,0.776471,0.114680,-1,2.445170,-1,...,-176.76700,-1,1498.9100,209.2980,113.9700,8067,2014,0,0,NaN
1,2,1,0,0.121569,0.666667,0.145098,0.002391,-1,0.107025,-1,...,-6.12066,-1,65.7881,59.8379,35.2981,4978,876,0,0,NaN
2,3,1,0,0.145098,0.117647,0.384314,0.009789,-1,0.394223,-1,...,159.45900,-1,152.9050,112.7490,38.6387,4591,864,0,0,NaN
3,4,1,0,0.505882,0.345098,0.984314,0.018379,-1,0.458355,-1,...,-314.37800,-1,140.9590,129.9710,75.3222,3752,449,0,0,NaN
4,5,1,0,0.188235,0.254902,0.521569,0.065204,-1,1.740540,-1,...,135.44100,-1,898.1310,332.6870,85.7558,1382,66,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3042,3043,1,1,0.466667,0.031372,0.113725,0.000995,-1,0.060854,-1,...,-101.58400,-1,135.9060,114.0030,55.3476,0,30,0,0,NaN
3043,3044,1,1,0.262745,0.396078,0.235294,0.000764,-1,0.056167,-1,...,-365.72500,-1,126.2430,106.0480,50.0009,0,30,0,0,NaN
3044,3045,1,1,0.113725,0.701961,0.796078,0.000156,-1,0.030248,-1,...,-387.95500,-1,98.2865,62.8914,21.0926,0,30,0,0,NaN
3045,3046,1,1,0.701961,0.819608,0.988235,0.000089,-1,0.013373,-1,...,-14.75220,-1,87.4924,36.0455,24.1364,0,30,0,0,NaN
3046,3047,1,1,0.403922,0.282353,0.027451,0.000161,-1,0.020313,-1,...,-225.12000,-1,88.4446,64.0180,39.8820,0,22,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.086275,0.254902,0.070588,0.002845,-1,0.139336,-1,...,-60.4693,-1,94.7616,65.4855,37.7360,4998,0,0,0,NaN
1,2,1,0,0.905882,0.600000,0.627451,0.000947,-1,0.054656,-1,...,-208.4180,-1,51.0896,47.7188,26.6984,4997,0,0,0,NaN
2,3,1,0,0.584314,0.125490,0.133333,0.002245,-1,0.102783,-1,...,708.1010,-1,75.5403,71.0451,44.5927,3857,0,0,0,NaN
3,4,1,0,0.478431,0.839216,0.960784,0.022052,-1,0.504582,-1,...,-97.2186,-1,157.0230,140.6280,101.4660,2027,1,0,0,NaN
4,5,1,0,0.000000,0.572549,0.572549,0.011778,-1,0.391171,-1,...,-106.9180,-1,214.3900,195.2560,84.7315,378,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,1441,1,1,0.713725,0.752941,0.694118,0.000440,-1,0.038463,-1,...,60.9861,-1,126.1440,72.1062,39.3372,0,30,0,0,NaN
1441,1442,1,1,0.847059,0.560784,0.854902,0.000802,-1,0.048989,-1,...,-387.7760,-1,130.1530,87.1459,58.0370,0,30,0,0,NaN
1442,1443,1,1,0.003922,0.145098,0.780392,0.001131,-1,0.066408,-1,...,-319.8600,-1,116.1350,109.7090,70.3817,1,30,0,0,NaN
1443,1444,1,1,0.725490,0.113725,0.400000,0.000329,-1,0.032966,-1,...,-382.9850,-1,143.4540,61.9984,32.6977,0,30,0,0,NaN
1444,1445,1,1,0.368627,0.031372,0.152941,0.000394,-1,0.043960,-1,...,-382.4510,-1,125.5620,78.5537,35.6030,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.031372,0.349020,0.949020,0.004355,-1,0.174698,-1,...,-128.2650,-1,87.3639,79.5018,42.1363,4913,3486,0,0,NaN
1,2,1,0,0.584314,0.203922,0.180392,0.012193,-1,0.333345,-1,...,-18.4769,-1,104.2230,93.0892,66.0216,4907,1981,0,0,NaN
2,3,1,0,0.988235,0.901961,0.341176,0.027790,-1,0.604746,-1,...,-223.3620,-1,169.1020,156.2880,99.9502,2537,296,0,0,NaN
3,4,1,0,0.094118,0.658824,0.156863,0.010985,-1,0.394026,-1,...,374.7610,-1,255.7680,81.6139,51.3069,1634,0,0,0,NaN
4,5,1,0,0.462745,0.858824,0.956863,0.007240,-1,0.260416,-1,...,-333.4850,-1,166.8350,108.6520,67.7041,1279,306,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4689,4690,1,1,0.090196,0.517647,0.890196,0.000092,-1,0.016414,-1,...,254.9050,-1,77.6305,38.2177,22.9044,0,30,0,0,NaN
4690,4691,1,1,0.988235,0.454902,0.560784,0.000381,-1,0.038049,-1,...,-331.5430,-1,89.4189,79.5713,40.2020,0,30,0,0,NaN
4691,4692,1,1,0.309804,0.156863,0.988235,0.000242,-1,0.026397,-1,...,-194.3870,-1,90.4117,64.9472,36.3261,0,30,0,0,NaN
4692,4693,1,1,0.050980,0.694118,0.000000,0.000190,-1,0.021429,-1,...,-160.7230,-1,70.8796,60.4596,37.1492,0,30,0,0,NaN
4693,4694,1,1,0.741176,0.450980,0.886275,0.000160,-1,0.019848,-1,...,-53.4418,-1,55.1724,52.3103,32.4579,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.294118,0.686275,0.627451,0.010362,-1,0.336335,-1,...,-318.1350,-1,107.2610,102.2590,59.7249,4745,3273,0,0,NaN
1,2,1,0,0.580392,0.635294,0.552941,0.031900,-1,0.681078,-1,...,36.4168,-1,204.1990,180.3050,84.7924,4306,536,0,0,NaN
2,3,1,0,0.737255,0.376471,0.725490,0.006960,-1,0.230314,-1,...,660.6470,-1,118.0440,91.5293,61.0685,4061,1712,0,0,NaN
3,4,1,0,0.866667,0.086275,0.662745,0.004504,-1,0.196250,-1,...,-211.4290,-1,84.9521,74.0302,45.0184,3931,2780,0,0,NaN
4,5,1,0,0.596078,0.286275,0.737255,0.002345,-1,0.153326,-1,...,-91.9565,-1,265.6030,51.0318,32.2096,1773,439,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2470,2471,1,1,0.560784,0.113725,0.752941,0.000192,-1,0.022805,-1,...,-370.6390,-1,84.5077,55.3140,30.3174,0,30,0,0,NaN
2471,2472,1,1,0.027451,0.737255,0.678431,0.000191,-1,0.029136,-1,...,302.3360,-1,113.6590,56.7093,33.9069,0,30,0,0,NaN
2472,2473,1,1,0.690196,0.211765,0.400000,0.000272,-1,0.024955,-1,...,-85.0507,-1,68.2704,60.3760,45.1969,0,30,0,0,NaN
2473,2474,1,1,0.043137,0.431373,0.984314,0.000185,-1,0.027290,-1,...,654.7490,-1,140.1220,56.4093,38.5100,0,30,0,0,NaN
2474,2475,1,1,0.992157,0.101961,0.843137,0.000571,-1,0.046106,-1,...,-88.4157,-1,122.5140,82.0067,51.3336,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.792157,0.537255,0.200000,0.022214,-1,0.607991,-1,...,12.78650,-1,160.6360,127.3750,76.7793,4767,315,0,0,NaN
1,2,1,0,0.090196,0.913725,0.196078,0.007324,-1,0.285871,-1,...,-82.97460,-1,154.8190,85.6241,56.6132,818,0,0,0,NaN
2,3,1,0,0.956863,0.466667,0.231373,0.007178,-1,0.284857,-1,...,-76.00510,-1,220.7570,93.7898,65.3159,424,0,0,0,NaN
3,4,1,0,0.517647,0.027451,0.725490,0.005190,-1,0.225859,-1,...,5.90211,-1,217.9150,95.6642,58.9029,395,0,0,0,NaN
4,5,1,0,0.258824,0.301961,0.113725,0.008190,-1,0.331745,-1,...,462.74300,-1,246.9780,109.2760,62.0591,395,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3782,3783,1,1,0.113725,0.486275,0.462745,0.000226,-1,0.027250,-1,...,-239.31700,-1,77.4876,67.8175,38.5952,0,30,0,0,NaN
3783,3784,1,1,0.913725,0.913725,0.105882,0.000628,-1,0.050143,-1,...,403.92800,-1,143.1570,86.2121,51.2376,0,30,0,0,NaN
3784,3785,1,1,0.866667,0.074510,0.960784,0.000180,-1,0.021566,-1,...,156.58100,-1,92.7154,47.8442,31.6005,0,30,0,0,NaN
3785,3786,1,1,0.658824,0.964706,0.796078,0.000241,-1,0.025503,-1,...,69.71910,-1,81.5662,62.4585,34.0648,0,30,0,0,NaN
3786,3787,1,1,0.607843,0.062745,0.988235,0.000139,-1,0.022097,-1,...,64.05370,-1,90.0637,59.8337,35.2147,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.745098,0.658824,0.952941,0.002397,-1,0.107294,-1,...,-156.3630,-1,141.2750,55.8994,34.2811,4994,0,0,0,NaN
1,2,1,0,0.956863,0.325490,0.325490,0.029194,-1,0.618616,-1,...,-258.0280,-1,152.7370,149.5790,100.8320,4809,5,0,0,NaN
2,3,1,0,0.964706,0.584314,0.239216,0.010855,-1,0.338671,-1,...,-326.6430,-1,121.5520,98.7356,67.8906,4717,6,0,0,NaN
3,4,1,0,0.972549,0.686275,0.180392,0.028343,-1,0.578180,-1,...,71.7750,-1,206.7100,175.7680,94.8339,4094,1,0,0,NaN
4,5,1,0,0.196078,0.235294,0.117647,0.016669,-1,0.440901,-1,...,-255.4550,-1,165.3710,121.7470,71.3029,3839,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,2934,1,1,0.584314,0.811765,0.458824,0.000088,-1,0.013472,-1,...,-120.7000,-1,50.6618,48.3046,23.7988,0,30,0,0,NaN
2934,2935,1,1,0.862745,0.180392,0.517647,0.000715,-1,0.048332,-1,...,638.6350,-1,127.8480,95.1324,54.1876,0,30,0,0,NaN
2935,2936,1,1,0.113725,0.749020,0.305882,0.000643,-1,0.048331,-1,...,-51.7222,-1,127.6380,83.6716,54.1086,0,30,0,0,NaN
2936,2937,1,1,0.019608,0.388235,0.478431,0.000243,-1,0.023251,-1,...,-46.7235,-1,74.4001,58.8699,39.9109,0,30,0,0,NaN
2937,2938,1,1,0.192157,0.043137,0.741176,0.000245,-1,0.029147,-1,...,185.3120,-1,98.5928,61.2223,28.4509,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.215686,0.043137,0.517647,0.026334,-1,0.633403,-1,...,16.6577,-1,213.0290,135.4540,89.3951,3343,85,0,0,NaN
1,2,1,0,0.247059,0.615686,0.345098,0.007860,-1,0.232472,-1,...,-239.8290,-1,112.0220,96.4073,75.2851,3162,923,0,0,NaN
2,3,1,0,0.058824,1.000000,0.066667,0.004896,-1,0.207383,-1,...,122.7470,-1,134.1260,99.7780,40.2587,2833,26,0,0,NaN
3,4,1,0,0.768627,0.145098,0.556863,0.012269,-1,0.410330,-1,...,-515.1020,-1,184.2860,120.6210,65.2906,1151,0,0,0,NaN
4,5,1,0,0.113725,0.329412,0.164706,0.008863,-1,0.296608,-1,...,-327.2270,-1,141.4710,139.0290,60.9282,544,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3606,3607,1,1,0.815686,0.345098,0.282353,0.000157,-1,0.021616,-1,...,-75.1492,-1,82.3668,59.2410,32.9943,0,30,0,0,NaN
3607,3608,1,1,0.200000,0.207843,0.027451,0.000483,-1,0.040101,-1,...,-527.8310,-1,106.5590,82.8105,39.5133,0,30,0,0,NaN
3608,3609,1,1,0.074510,0.866667,0.498039,0.000310,-1,0.032279,-1,...,-422.0180,-1,119.6780,69.1330,30.6249,0,30,0,0,NaN
3609,3610,1,1,0.133333,0.427451,0.058824,0.000062,-1,0.012222,-1,...,126.0510,-1,65.4729,35.5170,18.7769,0,30,0,0,NaN
3610,3611,1,1,0.282353,0.666667,0.549020,0.000596,-1,0.049653,-1,...,-174.3700,-1,126.1370,109.0280,52.4084,0,18,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.643137,0.031372,0.305882,0.022890,-1,0.501748,-1,...,-267.173,-1,143.9660,122.2680,88.8588,3766,168,0,0,NaN
1,2,1,0,0.066667,0.662745,0.721569,0.036793,-1,0.782328,-1,...,-267.260,-1,209.7330,171.7670,106.8800,2461,107,0,0,NaN
2,3,1,0,0.396078,0.658824,0.521569,0.015789,-1,0.459607,-1,...,-299.229,-1,249.9020,141.0770,73.8594,1628,214,0,0,NaN
3,4,1,0,0.117647,0.301961,0.266667,0.019231,-1,0.509001,-1,...,408.823,-1,379.8240,154.8500,95.5718,600,34,0,0,NaN
4,5,1,0,0.117647,0.501961,0.137255,0.006806,-1,0.277464,-1,...,295.866,-1,260.0360,104.7930,58.4644,417,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3439,3440,1,1,0.086275,0.117647,0.372549,0.000191,-1,0.026191,-1,...,643.023,-1,104.8210,57.8236,36.0738,0,30,0,0,NaN
3440,3441,1,1,0.807843,0.054902,0.196078,0.000537,-1,0.043388,-1,...,-275.928,-1,90.6058,84.6652,51.6738,0,30,0,0,NaN
3441,3442,1,1,0.117647,0.427451,0.270588,0.000338,-1,0.035461,-1,...,-254.915,-1,128.0680,82.7649,35.0984,0,30,0,0,NaN
3442,3443,1,1,0.639216,0.058824,0.925490,0.000272,-1,0.031080,-1,...,-368.577,-1,118.0520,67.8658,39.1232,0,30,0,0,NaN
3443,3444,1,1,0.094118,0.619608,0.196078,0.000604,-1,0.042813,-1,...,-101.439,-1,118.7210,93.8420,60.5331,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.427451,0.258824,0.086275,0.013594,-1,0.414103,-1,...,-421.3050,-1,268.0150,98.8611,59.3037,4166,211,0,0,NaN
1,2,1,0,0.094118,0.670588,0.486275,0.004689,-1,0.189412,-1,...,112.7520,-1,138.2080,74.6090,44.9370,1027,0,0,0,NaN
2,3,1,0,0.956863,0.282353,0.678431,0.002475,-1,0.132015,-1,...,304.2540,-1,99.8910,47.4184,29.5069,773,0,0,0,NaN
3,4,1,0,0.031372,0.121569,0.874510,0.005819,-1,0.202445,-1,...,-162.2120,-1,129.3720,90.1926,59.5500,553,1,0,0,NaN
4,5,1,0,0.498039,0.247059,0.066667,0.004432,-1,0.207058,-1,...,162.4380,-1,162.3210,83.4786,51.9854,469,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3596,3597,1,1,0.345098,0.160784,0.298039,0.000643,-1,0.050579,-1,...,623.0810,-1,153.0820,88.7998,38.6282,0,30,0,0,NaN
3597,3598,1,1,0.674510,0.172549,0.192157,0.000136,-1,0.018848,-1,...,-291.4810,-1,102.0100,45.1882,25.3542,0,30,0,0,NaN
3598,3599,1,1,0.831373,0.109804,0.501961,0.000148,-1,0.018376,-1,...,-701.9270,-1,83.8659,51.2237,25.5536,0,30,0,0,NaN
3599,3600,1,1,0.321569,0.717647,0.149020,0.000151,-1,0.023912,-1,...,273.8170,-1,111.6990,49.1598,21.7202,0,30,0,0,NaN
3600,3601,1,1,0.133333,0.913725,0.203922,0.000337,-1,0.030208,-1,...,-34.5955,-1,97.6601,69.7304,48.1497,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.078431,0.941176,0.972549,0.001049,-1,0.056029,-1,...,-54.0005,-1,78.2437,45.7409,29.4788,4968,229,0,0,NaN
1,2,1,0,0.635294,0.149020,0.909804,0.008948,-1,0.282323,-1,...,-155.5020,-1,107.4970,100.5790,60.7881,4870,1550,0,0,NaN
2,3,1,0,0.952941,0.760784,0.203922,0.017751,-1,0.466577,-1,...,-12.0641,-1,196.1910,131.1840,79.8566,1619,50,0,0,NaN
3,4,1,0,0.847059,0.807843,0.047059,0.004310,-1,0.207659,-1,...,352.0210,-1,189.4340,65.6810,41.0111,959,0,0,0,NaN
4,5,1,0,0.207843,0.070588,0.654902,0.020118,-1,0.494477,-1,...,19.9587,-1,211.4140,159.1310,95.6077,925,74,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3564,3565,1,1,0.160784,0.337255,0.717647,0.000096,-1,0.019023,-1,...,-83.3502,-1,138.4420,44.1363,21.9839,0,30,0,0,NaN
3565,3566,1,1,0.133333,0.164706,0.007843,0.000147,-1,0.023183,-1,...,343.4750,-1,110.3290,44.7555,22.8783,0,30,0,0,NaN
3566,3567,1,1,0.945098,0.580392,0.698039,0.000270,-1,0.034086,-1,...,-302.3260,-1,126.1560,69.5071,41.0139,0,30,0,0,NaN
3567,3568,1,1,0.439216,0.247059,0.870588,0.000420,-1,0.038084,-1,...,378.0930,-1,98.9536,83.8539,43.1229,0,30,0,0,NaN
3568,3569,1,1,0.180392,0.521569,0.019608,0.000223,-1,0.029401,-1,...,363.9220,-1,105.1770,63.8645,29.9004,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.423529,0.823529,0.329412,0.031589,-1,0.736753,-1,...,130.6190,-1,253.4630,154.6710,89.1085,2502,210,0,0,NaN
1,2,1,0,0.576471,0.862745,0.788235,0.012588,-1,0.391715,-1,...,66.4139,-1,221.9360,121.7920,77.5939,768,0,0,0,NaN
2,3,1,0,0.121569,0.843137,0.552941,0.025217,-1,0.592786,-1,...,-356.6500,-1,272.7630,211.5990,119.7220,573,51,0,0,NaN
3,4,1,0,0.823529,0.537255,0.501961,0.012710,-1,0.335772,-1,...,676.0000,-1,191.8860,175.5800,109.8920,498,42,0,0,NaN
4,5,1,0,0.239216,0.443137,0.454902,0.001956,-1,0.095073,-1,...,-120.1310,-1,97.5279,70.4129,44.8569,403,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3962,3963,1,1,0.462745,0.592157,0.960784,0.000034,-1,0.006680,-1,...,-93.1781,-1,45.4763,30.9420,19.3615,0,30,0,0,NaN
3963,3964,1,1,0.929412,0.803922,0.062745,0.000448,-1,0.036318,-1,...,-147.3820,-1,83.6830,79.1933,40.7667,0,30,0,0,NaN
3964,3965,1,1,0.650980,0.454902,0.964706,0.000121,-1,0.015406,-1,...,-214.7160,-1,62.9867,46.9335,28.3875,0,30,0,0,NaN
3965,3966,1,1,0.529412,0.400000,0.709804,0.000108,-1,0.019098,-1,...,-40.2756,-1,96.3827,46.9347,19.4118,0,30,0,0,NaN
3966,3967,1,1,0.450980,0.650980,0.278431,0.000229,-1,0.032213,-1,...,-478.9210,-1,128.0570,52.6624,23.2257,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.058824,0.376471,0.635294,0.008736,-1,0.300525,-1,...,-254.659,-1,161.8900,103.7430,62.9364,614,0,0,0,NaN
1,2,1,0,0.768627,0.576471,0.266667,0.006452,-1,0.250601,-1,...,-299.934,-1,163.8080,110.7840,74.0443,336,0,0,0,NaN
2,3,1,0,0.796078,0.670588,0.623529,0.004823,-1,0.223686,-1,...,-125.310,-1,180.2290,116.2010,55.7790,309,0,0,0,NaN
3,4,1,0,0.031372,0.270588,0.854902,0.003771,-1,0.199743,-1,...,-481.651,-1,262.6600,81.2865,51.9366,300,0,0,0,NaN
4,5,1,0,0.419608,0.474510,0.780392,0.015116,-1,0.427237,-1,...,-327.935,-1,246.2070,193.1850,105.5360,294,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2904,2905,1,1,0.576471,0.019608,0.121569,0.000464,-1,0.038188,-1,...,589.749,-1,123.9740,78.2680,51.5859,0,30,0,0,NaN
2905,2906,1,1,0.133333,0.517647,0.050980,0.000223,-1,0.026772,-1,...,291.985,-1,85.0477,53.8790,31.8656,0,30,0,0,NaN
2906,2907,1,1,0.960784,0.274510,0.843137,0.000060,-1,0.010916,-1,...,-310.285,-1,66.4211,32.8517,22.3569,0,30,0,0,NaN
2907,2908,1,1,0.725490,0.243137,0.266667,0.000573,-1,0.046262,-1,...,-336.121,-1,109.1450,94.8951,62.3654,0,30,0,0,NaN
2908,2909,1,1,0.517647,0.721569,0.976471,0.000285,-1,0.035285,-1,...,-366.584,-1,131.1740,71.5967,37.9278,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.858824,0.941176,0.470588,0.044039,-1,0.785972,-1,...,-202.8340,-1,198.540,188.4060,128.8900,3182,127,0,0,NaN
1,2,1,0,0.380392,0.047059,0.478431,0.030499,-1,0.623425,-1,...,-251.1850,-1,198.659,165.0970,109.7960,2356,267,0,0,NaN
2,3,1,0,0.564706,0.152941,0.498039,0.006080,-1,0.252288,-1,...,-392.8200,-1,226.553,86.3310,50.4936,966,0,0,0,NaN
3,4,1,0,0.227451,0.301961,0.427451,0.004002,-1,0.166123,-1,...,-50.6484,-1,117.552,91.2494,51.8203,657,0,0,0,NaN
4,5,1,0,0.031372,0.694118,0.011765,0.010081,-1,0.370857,-1,...,414.3040,-1,302.519,108.5620,61.3720,590,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,1038,1,1,0.203922,0.133333,0.741176,0.000260,-1,0.032766,-1,...,-409.2010,-1,113.275,58.4508,30.2629,0,30,0,0,NaN
1038,1039,1,1,0.788235,0.211765,0.870588,0.000615,-1,0.047574,-1,...,615.7750,-1,107.265,93.6935,49.3626,2,30,0,0,NaN
1039,1040,1,1,0.827451,0.600000,0.443137,0.000745,-1,0.051754,-1,...,689.6170,-1,107.688,104.4950,49.5814,0,30,0,0,NaN
1040,1041,1,1,0.647059,0.309804,0.803922,0.000356,-1,0.036821,-1,...,-388.3290,-1,115.358,82.2956,31.8849,0,30,0,0,NaN
1041,1042,1,1,0.321569,0.980392,0.305882,0.000582,-1,0.050567,-1,...,-342.1470,-1,112.944,101.7710,44.3510,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.356863,0.925490,0.231373,0.001442,-1,0.075306,-1,...,-176.9020,-1,69.3237,55.3218,35.1483,4999,161,0,0,NaN
1,2,1,0,0.850980,0.188235,0.941176,0.021511,-1,0.540057,-1,...,-313.8700,-1,216.9920,142.2270,97.3481,2040,21,0,0,NaN
2,3,1,0,0.164706,0.031372,0.137255,0.001781,-1,0.081712,-1,...,695.5460,-1,71.6686,59.5592,46.6156,1252,147,0,0,NaN
3,4,1,0,0.043137,0.105882,0.760784,0.009755,-1,0.310439,-1,...,77.6952,-1,136.9830,98.5647,68.9434,991,0,0,0,NaN
4,5,1,0,0.141176,0.874510,0.901961,0.009597,-1,0.340488,-1,...,-359.2960,-1,163.6880,99.3785,65.2845,878,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2118,2119,1,1,0.125490,0.725490,0.780392,0.001022,-1,0.057502,-1,...,-235.7580,-1,114.3650,104.1920,72.0996,0,30,0,0,NaN
2119,2120,1,1,0.235294,0.588235,0.866667,0.000346,-1,0.035691,-1,...,464.0850,-1,141.3970,73.6279,35.6803,0,30,0,0,NaN
2120,2121,1,1,0.466667,0.490196,0.513725,0.000189,-1,0.022728,-1,...,-462.9960,-1,78.3086,55.9701,26.3371,0,30,0,0,NaN
2121,2122,1,1,0.047059,0.537255,0.698039,0.000225,-1,0.023947,-1,...,70.7466,-1,82.6445,64.0919,37.2819,0,30,0,0,NaN
2122,2123,1,1,0.364706,0.807843,0.882353,0.000250,-1,0.033180,-1,...,368.6140,-1,122.1870,63.7433,23.5852,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.207843,0.643137,0.090196,0.008824,-1,0.324197,-1,...,175.1570,-1,203.022,113.2880,58.8854,671,0,0,0,NaN
1,2,1,0,0.776471,0.160784,0.403922,0.004399,-1,0.223102,-1,...,-332.4510,-1,166.209,80.7851,53.4699,504,0,0,0,NaN
2,3,1,0,0.678431,0.258824,0.388235,0.010247,-1,0.369307,-1,...,-396.4970,-1,212.543,187.8610,68.8181,488,3,0,0,NaN
3,4,1,0,0.643137,0.086275,0.921569,0.004525,-1,0.184343,-1,...,-71.4356,-1,114.761,90.2829,55.0347,381,2,0,0,NaN
4,5,1,0,0.898039,0.298039,0.294118,0.007686,-1,0.323563,-1,...,-413.4110,-1,180.830,175.0330,69.6615,354,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4905,4906,1,1,0.027451,0.933333,0.337255,0.000327,-1,0.032706,-1,...,-426.3830,-1,122.444,80.6640,39.1336,0,30,0,0,NaN
4906,4907,1,1,0.227451,0.105882,0.023529,0.000241,-1,0.028955,-1,...,303.7310,-1,105.387,56.6407,30.5208,0,30,0,0,NaN
4907,4908,1,1,0.858824,0.235294,0.933333,0.000565,-1,0.041783,-1,...,57.3526,-1,102.256,84.1259,55.4799,0,30,0,0,NaN
4908,4909,1,1,0.752941,0.133333,0.431373,0.000139,-1,0.020783,-1,...,-408.2090,-1,106.357,41.7082,22.3733,0,30,0,0,NaN
4909,4910,1,1,0.607843,0.282353,0.858824,0.000450,-1,0.038964,-1,...,359.6190,-1,115.813,75.3600,42.2036,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.266667,0.929412,0.203922,0.009830,-1,0.345694,-1,...,187.52800,-1,177.9030,84.2694,54.9371,4502,680,0,0,NaN
1,2,1,0,0.552941,0.549020,0.458824,0.001144,-1,0.063187,-1,...,700.91800,-1,69.9811,57.8687,33.4690,2172,291,0,0,NaN
2,3,1,0,0.819608,0.278431,0.333333,0.026988,-1,0.653595,-1,...,-341.94800,-1,239.9170,152.3330,84.0541,2156,54,0,0,NaN
3,4,1,0,0.886275,0.054902,0.752941,0.015860,-1,0.511558,-1,...,-9.85906,-1,291.5420,112.7000,74.8009,816,0,0,0,NaN
4,5,1,0,0.792157,0.011765,0.003922,0.006376,-1,0.272323,-1,...,-380.51000,-1,169.5710,80.9622,51.5931,800,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3261,3262,1,1,0.760784,0.811765,0.364706,0.000371,-1,0.035332,-1,...,-359.18100,-1,105.2630,68.5205,35.7333,0,30,0,0,NaN
3262,3263,1,1,0.913725,0.552941,0.301961,0.000151,-1,0.022225,-1,...,239.12400,-1,111.6570,56.5472,19.5804,0,30,0,0,NaN
3263,3264,1,1,0.309804,0.811765,0.956863,0.000126,-1,0.018292,-1,...,-346.69600,-1,87.2012,47.7284,28.9776,0,30,0,0,NaN
3264,3265,1,1,0.941176,0.941176,0.349020,0.000282,-1,0.029506,-1,...,-382.06200,-1,139.0970,66.4071,29.3133,0,30,0,0,NaN
3265,3266,1,1,0.890196,0.945098,0.215686,0.000073,-1,0.013204,-1,...,-206.47200,-1,65.3589,37.0926,23.0578,0,28,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,0,1,-1,0.000000,0.000000,0.000000,-1.000000,-1,-1.000000,-1,...,0.00000,-1,0.0000,0.0000,0.0000,0,0,0,0,NaN
1,1,1,0,0.737255,0.043137,0.474510,0.024435,-1,0.698889,-1,...,640.92000,-1,340.3720,173.4860,63.4027,3172,215,0,0,NaN
2,2,1,0,0.203922,0.392157,0.176471,0.014141,-1,0.370698,-1,...,-6.23529,-1,180.3070,113.6890,75.9818,2254,32,0,0,NaN
3,3,1,0,0.690196,0.517647,0.584314,0.004476,-1,0.200808,-1,...,238.93900,-1,122.6970,69.2764,43.1541,748,0,0,0,NaN
4,4,1,0,0.654902,0.976471,0.431373,0.001389,-1,0.089774,-1,...,-504.88300,-1,161.0590,59.0114,36.7636,452,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,1007,1,1,0.980392,0.843137,0.109804,0.000312,-1,0.031520,-1,...,244.74000,-1,107.8830,70.7957,41.2601,0,30,0,0,NaN
1008,1008,1,1,0.862745,0.294118,0.176471,0.000236,-1,0.030825,-1,...,-31.75880,-1,101.8840,58.5284,28.7585,0,30,0,0,NaN
1009,1009,1,1,0.352941,0.007843,0.741176,0.000329,-1,0.033237,-1,...,-275.40800,-1,136.6210,83.4117,47.9152,0,30,0,0,NaN
1010,1010,1,1,0.172549,0.207843,0.815686,0.000425,-1,0.035996,-1,...,-516.03400,-1,98.7385,75.7701,49.8200,0,30,0,0,NaN
1011,1011,1,1,0.972549,0.317647,0.611765,0.000366,-1,0.034104,-1,...,-97.28960,-1,87.7687,70.1342,43.5160,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.447059,0.596078,0.690196,0.032495,-1,0.761417,-1,...,-190.1080,-1,188.1710,153.6120,77.0801,4661,1693,0,0,NaN
1,2,1,0,0.788235,0.039216,0.729412,0.026754,-1,0.551406,-1,...,-253.0710,-1,199.4800,177.4970,122.4570,970,28,0,0,NaN
2,3,1,0,0.286275,0.537255,0.690196,0.005613,-1,0.233078,-1,...,-310.6000,-1,159.4680,85.3275,51.7289,775,0,0,0,NaN
3,4,1,0,0.400000,0.345098,0.172549,0.009821,-1,0.335424,-1,...,-121.0810,-1,157.3890,127.1090,76.8253,566,0,0,0,NaN
4,5,1,0,0.219608,0.192157,0.411765,0.008701,-1,0.323802,-1,...,238.8700,-1,253.1510,115.1700,71.3906,509,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1142,1143,1,1,0.231373,0.125490,0.972549,0.000158,-1,0.019437,-1,...,-218.6230,-1,70.1856,52.3351,30.2094,0,30,0,0,NaN
1143,1144,1,1,0.309804,0.960784,0.262745,0.000498,-1,0.041188,-1,...,293.4610,-1,148.4510,82.0146,46.3002,0,30,0,0,NaN
1144,1145,1,1,0.188235,0.298039,0.972549,0.000224,-1,0.023979,-1,...,-106.7890,-1,82.1722,56.3832,32.7097,0,30,0,0,NaN
1145,1146,1,1,0.517647,0.384314,0.956863,0.000545,-1,0.048154,-1,...,20.8461,-1,120.1120,94.8387,42.5323,0,30,0,0,NaN
1146,1147,1,1,0.666667,0.749020,0.298039,0.000547,-1,0.044669,-1,...,-337.7720,-1,141.4230,100.9620,39.5557,2,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.403922,0.043137,0.909804,0.012308,-1,0.386420,-1,...,-221.9110,-1,108.4470,96.2769,69.8335,3818,3357,0,0,NaN
1,2,1,0,0.333333,0.949020,0.623529,0.021622,-1,0.530113,-1,...,-219.6050,-1,230.1320,151.5230,90.8863,1149,1405,0,0,NaN
2,3,1,0,0.101961,0.356863,0.862745,0.013448,-1,0.384618,-1,...,-60.5613,-1,159.5270,141.0920,89.2459,622,0,0,0,NaN
3,4,1,0,0.419608,0.584314,0.886275,0.007139,-1,0.274725,-1,...,145.9110,-1,199.8900,94.8048,58.5644,587,0,0,0,NaN
4,5,1,0,0.552941,0.870588,0.556863,0.003275,-1,0.164672,-1,...,197.0660,-1,223.4210,80.2119,55.1552,373,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2562,2563,1,1,0.709804,0.200000,0.035294,0.000182,-1,0.027724,-1,...,-481.3740,-1,88.4463,56.1455,24.9641,0,30,0,0,NaN
2563,2564,1,1,0.690196,0.105882,0.890196,0.000547,-1,0.040966,-1,...,-257.4120,-1,151.8190,77.2442,50.0171,0,30,0,0,NaN
2564,2565,1,1,0.909804,0.615686,0.745098,0.000269,-1,0.031338,-1,...,-277.9390,-1,92.2323,59.4916,40.1143,2,30,0,0,NaN
2565,2566,1,1,0.992157,0.149020,0.956863,0.000377,-1,0.035494,-1,...,-555.9830,-1,117.1570,64.8309,39.1015,0,30,0,0,NaN
2566,2567,1,1,0.270588,0.478431,0.325490,0.000571,-1,0.045734,-1,...,65.3508,-1,104.7190,100.9370,55.2215,0,22,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.094118,0.521569,0.121569,0.056163,-1,1.503670,-1,...,-100.9930,-1,1005.8200,162.2670,105.8830,7209,567,0,0,NaN
1,2,1,0,0.156863,0.600000,0.388235,0.004191,-1,0.226865,-1,...,613.0630,-1,257.3320,71.4223,36.3598,2872,170,0,0,NaN
2,3,1,0,0.580392,0.823529,0.247059,0.022018,-1,0.544181,-1,...,95.7691,-1,209.4400,140.5170,92.0475,1838,24,0,0,NaN
3,4,1,0,0.023529,0.392157,0.737255,0.023257,-1,0.549267,-1,...,-268.2260,-1,175.6480,144.3840,85.4381,1345,1,0,0,NaN
4,5,1,0,0.356863,0.603922,0.615686,0.012633,-1,0.383054,-1,...,-360.0730,-1,142.4870,100.8530,60.7805,1203,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2044,2045,1,1,0.141176,0.215686,0.800000,0.000237,-1,0.028801,-1,...,-300.5000,-1,102.6630,61.4568,34.0607,0,30,0,0,NaN
2045,2046,1,1,0.729412,0.658824,0.811765,0.000261,-1,0.026028,-1,...,-63.2510,-1,111.7520,76.0334,40.7488,0,30,0,0,NaN
2046,2047,1,1,0.725490,0.101961,0.337255,0.000292,-1,0.029056,-1,...,90.0066,-1,123.3430,68.5059,31.2389,0,30,0,0,NaN
2047,2048,1,1,0.325490,0.964706,0.509804,0.000229,-1,0.026322,-1,...,-324.7580,-1,80.3183,55.4744,33.9077,0,30,0,0,NaN
2048,2049,1,1,0.741176,0.341176,0.007843,0.000348,-1,0.032193,-1,...,-340.8340,-1,102.1550,77.2526,39.8158,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.937255,0.964706,1.000000,0.020009,-1,0.476284,-1,...,2.3668,-1,206.9570,181.8290,118.0420,438,3,0,0,NaN
1,2,1,0,0.450980,0.713725,0.266667,0.010292,-1,0.336954,-1,...,-24.6526,-1,185.3310,145.8510,86.8237,349,1,0,0,NaN
2,3,1,0,0.647059,0.780392,0.423529,0.004086,-1,0.220570,-1,...,-531.1160,-1,369.0640,81.0892,53.8487,306,0,0,0,NaN
3,4,1,0,0.227451,0.521569,0.321569,0.005348,-1,0.257193,-1,...,-208.1360,-1,218.8540,117.9110,66.7898,299,0,0,0,NaN
4,5,1,0,0.392157,0.650980,0.415686,0.008081,-1,0.256846,-1,...,-157.9490,-1,159.6550,146.1640,87.4842,284,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3059,3060,1,1,0.980392,0.160784,0.117647,0.000879,-1,0.054979,-1,...,539.3680,-1,107.5680,93.3411,53.9943,0,30,0,0,NaN
3060,3061,1,1,0.537255,0.866667,0.525490,0.000483,-1,0.042283,-1,...,536.3110,-1,131.5950,78.6291,33.7142,0,30,0,0,NaN
3061,3062,1,1,0.784314,0.423529,0.082353,0.000497,-1,0.036684,-1,...,-171.9850,-1,85.0427,80.4258,46.9618,0,30,0,0,NaN
3062,3063,1,1,0.623529,0.462745,0.843137,0.000413,-1,0.036389,-1,...,-56.0839,-1,140.2470,68.6022,41.7561,0,30,0,0,NaN
3063,3064,1,1,0.298039,0.015686,0.584314,0.000695,-1,0.049630,-1,...,528.2230,-1,126.9620,87.2030,52.3584,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.988235,0.678431,0.239216,0.000798,-1,0.049738,-1,...,-71.6908,-1,87.3583,46.8217,26.0929,4985,18,0,0,NaN
1,2,1,0,0.062745,0.862745,0.447059,0.004483,-1,0.181636,-1,...,-249.4870,-1,89.0810,81.0347,45.9482,4938,3503,0,0,NaN
2,3,1,0,0.996078,0.545098,0.862745,0.008040,-1,0.251724,-1,...,-264.8570,-1,112.1190,106.1530,59.9768,4895,1791,0,0,NaN
3,4,1,0,0.007843,0.800000,0.898039,0.020755,-1,0.506651,-1,...,-206.5650,-1,164.4270,129.4220,72.9944,4887,699,0,0,NaN
4,5,1,0,0.568627,0.780392,0.160784,0.005455,-1,0.223283,-1,...,-343.3370,-1,95.9662,78.6926,49.4482,4571,1026,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2352,2353,1,1,0.874510,0.043137,0.619608,0.000147,-1,0.017114,-1,...,-211.4080,-1,62.1793,49.0636,28.1299,0,30,0,0,NaN
2353,2354,1,1,0.227451,0.458824,0.819608,0.000224,-1,0.027883,-1,...,348.0080,-1,120.2760,58.3095,36.3646,0,30,0,0,NaN
2354,2355,1,1,0.039216,0.752941,0.756863,0.000264,-1,0.028707,-1,...,223.2700,-1,104.0780,57.7403,28.2376,0,30,0,0,NaN
2355,2356,1,1,0.831373,0.898039,0.996078,0.000076,-1,0.016219,-1,...,159.5080,-1,84.4954,38.6413,18.3065,0,30,0,0,NaN
2356,2357,1,1,0.207843,0.552941,0.745098,0.000135,-1,0.019157,-1,...,477.3290,-1,87.3905,61.6444,27.7421,0,17,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.737255,0.043137,0.658824,0.012849,-1,0.542029,-1,...,-375.1610,-1,249.6770,248.4440,91.6563,690,2,0,0,NaN
1,2,1,0,0.760784,0.356863,0.211765,0.007406,-1,0.274273,-1,...,-96.2304,-1,143.4610,106.2960,67.1006,420,0,0,0,NaN
2,3,1,0,0.839216,0.376471,0.568627,0.006369,-1,0.274260,-1,...,82.5938,-1,184.3660,109.9080,66.5583,361,4,0,0,NaN
3,4,1,0,0.341176,0.172549,0.039216,0.008248,-1,0.339800,-1,...,293.6600,-1,310.2540,105.7570,63.3213,356,0,0,0,NaN
4,5,1,0,0.419608,0.501961,0.211765,0.003315,-1,0.168763,-1,...,-305.1480,-1,154.5890,82.5520,53.6161,355,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5368,5369,1,1,0.349020,0.074510,0.035294,0.000080,-1,0.013536,-1,...,-345.0220,-1,81.4266,39.7676,19.9739,0,30,0,0,NaN
5369,5370,1,1,0.800000,0.694118,0.541176,0.000186,-1,0.023661,-1,...,-212.5270,-1,97.3948,47.9941,29.5704,0,30,0,0,NaN
5370,5371,1,1,0.380392,0.031372,0.737255,0.000181,-1,0.025832,-1,...,-321.1960,-1,118.1040,51.7700,34.0938,0,30,0,0,NaN
5371,5372,1,1,0.858824,0.568627,0.278431,0.000445,-1,0.038922,-1,...,-412.5080,-1,154.3430,67.3372,45.8197,0,30,0,0,NaN
5372,5373,1,1,0.874510,0.764706,0.752941,0.000140,-1,0.025821,-1,...,-381.8070,-1,124.0430,55.1750,22.8622,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.560784,0.952941,0.164706,0.008087,-1,0.302276,-1,...,90.3593,-1,137.8810,83.9006,46.9253,4848,566,0,0,NaN
1,2,1,0,0.643137,0.972549,0.666667,0.018652,-1,0.491375,-1,...,-141.8280,-1,137.5420,126.2380,78.3285,4391,464,0,0,NaN
2,3,1,0,0.917647,0.423529,0.478431,0.021657,-1,0.549263,-1,...,-42.4823,-1,231.3650,164.2550,95.2461,700,0,0,0,NaN
3,4,1,0,0.533333,0.074510,0.156863,0.003122,-1,0.176340,-1,...,-644.8910,-1,299.5530,76.8373,49.7596,608,0,0,0,NaN
4,5,1,0,0.196078,0.470588,0.349020,0.013372,-1,0.383959,-1,...,22.9250,-1,174.0370,137.0650,85.7482,575,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3103,3104,1,1,0.219608,0.301961,0.701961,0.000354,-1,0.036646,-1,...,-36.4295,-1,96.1259,72.6407,28.3492,0,30,0,0,NaN
3104,3105,1,1,0.988235,0.415686,0.058824,0.000472,-1,0.045134,-1,...,-335.0510,-1,125.3540,88.7216,43.3784,0,30,0,0,NaN
3105,3106,1,1,0.800000,0.160784,0.474510,0.000517,-1,0.046465,-1,...,168.5450,-1,127.3290,88.7421,33.5975,0,30,0,0,NaN
3106,3107,1,1,0.411765,1.000000,0.364706,0.000959,-1,0.057397,-1,...,620.8190,-1,124.3350,101.0580,65.4492,0,30,0,0,NaN
3107,3108,1,1,0.713725,0.666667,0.286275,0.000434,-1,0.039825,-1,...,-258.7430,-1,130.6050,69.6333,39.0522,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.388235,0.854902,0.101961,0.000874,-1,0.057831,-1,...,-134.2930,-1,53.5006,47.9757,24.4705,4992,0,0,0,NaN
1,2,1,0,0.925490,0.000000,0.431373,0.007358,-1,0.289838,-1,...,-265.8700,-1,110.5900,69.5469,41.9873,4931,1519,0,0,NaN
2,3,1,0,0.639216,0.431373,0.941176,0.016483,-1,0.454505,-1,...,120.1290,-1,124.5440,115.3150,70.1752,4660,432,0,0,NaN
3,4,1,0,0.698039,0.552941,0.513725,0.023304,-1,0.694390,-1,...,232.9570,-1,407.7000,109.4310,66.3463,4547,288,0,0,NaN
4,5,1,0,0.823529,0.694118,0.176471,0.019772,-1,0.640576,-1,...,141.2840,-1,329.9810,135.0300,64.8030,4211,379,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4060,4061,1,1,0.403922,0.462745,0.552941,0.000462,-1,0.036206,-1,...,-167.4830,-1,92.0912,72.0181,47.3339,0,30,0,0,NaN
4061,4062,1,1,0.564706,0.545098,0.482353,0.000388,-1,0.041725,-1,...,-191.0400,-1,96.9377,80.4063,44.6582,0,30,0,0,NaN
4062,4063,1,1,0.843137,0.388235,0.003922,0.000689,-1,0.048203,-1,...,-337.0860,-1,116.1400,87.9934,53.3791,1,30,0,0,NaN
4063,4064,1,1,0.239216,0.000000,0.200000,0.000287,-1,0.028513,-1,...,-105.0750,-1,81.4981,65.5365,41.1522,0,30,0,0,NaN
4064,4065,1,1,0.882353,0.176471,0.647059,0.000191,-1,0.022465,-1,...,-30.5446,-1,63.6349,61.5888,35.0519,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.411765,0.149020,0.854902,0.011369,-1,0.371988,-1,...,-195.179,-1,132.6630,124.2410,68.9940,1632,2,0,0,NaN
1,2,1,0,0.317647,0.298039,0.858824,0.017323,-1,0.476953,-1,...,-222.753,-1,148.3350,136.9460,63.9989,1463,46,0,0,NaN
2,3,1,0,0.427451,0.996078,0.054902,0.069960,-1,1.346710,-1,...,-181.097,-1,477.6340,348.8410,215.5020,983,71,0,0,NaN
3,4,1,0,0.858824,0.086275,0.470588,0.004889,-1,0.219798,-1,...,-347.649,-1,151.2240,105.0440,52.2522,443,1,0,0,NaN
4,5,1,0,0.043137,0.556863,0.219608,0.013075,-1,0.443441,-1,...,313.221,-1,342.7170,137.0190,82.5279,436,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6993,6994,1,1,0.686275,0.090196,0.741176,0.000335,-1,0.040578,-1,...,-364.771,-1,88.0425,84.8308,36.9183,0,30,0,0,NaN
6994,6995,1,1,0.066667,0.290196,0.505882,0.000496,-1,0.040507,-1,...,-338.919,-1,112.7260,74.6373,48.9334,0,30,0,0,NaN
6995,6996,1,1,0.305882,0.745098,0.152941,0.000079,-1,0.014124,-1,...,-215.347,-1,58.4747,57.7965,19.0086,0,30,0,0,NaN
6996,6997,1,1,0.023529,0.698039,0.168627,0.000786,-1,0.056178,-1,...,-242.569,-1,108.0320,102.0210,61.6981,0,30,0,0,NaN
6997,6998,1,1,0.976471,0.356863,0.517647,0.000445,-1,0.037158,-1,...,-114.154,-1,88.3194,79.5087,41.6466,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,0,1,-1,0.000000,0.000000,0.000000,-1.000000,-1,-1.000000,-1,...,0.0000,-1,0.0000,0.0000,0.0000,0,0,0,0,NaN
1,1,1,0,0.086275,0.717647,0.333333,0.002074,-1,0.099587,-1,...,-256.0380,-1,70.3629,58.9420,34.0678,4998,788,0,0,NaN
2,2,1,0,0.568627,0.654902,0.019608,0.021898,-1,0.552935,-1,...,-261.7740,-1,133.3530,131.3600,87.6942,4717,238,0,0,NaN
3,3,1,0,0.670588,0.960784,0.168627,0.015089,-1,0.368493,-1,...,-113.6330,-1,183.8950,176.2080,117.8950,398,8,0,0,NaN
4,4,1,0,0.682353,0.027451,0.705882,0.005885,-1,0.271815,-1,...,261.5590,-1,243.3720,110.6080,60.4678,254,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,460,1,1,0.513725,0.517647,0.709804,0.000402,-1,0.037385,-1,...,-244.1260,-1,89.1725,83.4687,41.3704,0,30,0,0,NaN
461,461,1,1,0.643137,0.466667,0.200000,0.000777,-1,0.050273,-1,...,101.5130,-1,100.1350,94.8778,60.7964,0,30,0,0,NaN
462,462,1,1,0.105882,0.803922,0.909804,0.000377,-1,0.037582,-1,...,-322.9280,-1,103.7240,80.9762,30.6646,0,30,0,0,NaN
463,463,1,1,0.631373,0.294118,0.788235,0.000667,-1,0.047868,-1,...,33.7632,-1,111.8830,98.6345,46.8341,0,30,0,0,NaN
464,464,1,1,0.003922,0.615686,1.000000,0.000415,-1,0.043063,-1,...,-368.6210,-1,87.8914,86.0982,38.4733,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.019608,0.545098,0.239216,0.009509,-1,0.420349,-1,...,-46.2577,-1,241.3690,88.9539,60.7702,5270,3064,0,0,NaN
1,2,1,0,0.047059,0.878431,0.266667,0.003896,-1,0.162538,-1,...,17.5313,-1,77.8687,75.9777,46.9073,5000,2251,0,0,NaN
2,3,1,0,0.568627,0.768627,0.925490,0.003354,-1,0.147546,-1,...,-203.9590,-1,65.2712,56.4947,36.4177,4996,2510,0,0,NaN
3,4,1,0,0.411765,0.721569,0.611765,0.012185,-1,0.337485,-1,...,90.1230,-1,130.9590,101.1420,69.6603,4911,826,0,0,NaN
4,5,1,0,0.192157,0.552941,0.733333,0.006239,-1,0.225668,-1,...,-19.1775,-1,90.5222,78.8265,54.8855,4752,1611,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1764,1765,1,1,0.403922,0.792157,0.964706,0.000777,-1,0.055860,-1,...,-328.3930,-1,105.1960,100.3060,62.3986,0,30,0,0,NaN
1765,1766,1,1,0.988235,0.396078,0.945098,0.000206,-1,0.027213,-1,...,144.3540,-1,96.3038,76.9860,24.5651,0,30,0,0,NaN
1766,1767,1,1,0.949020,0.909804,0.223529,0.000202,-1,0.025666,-1,...,-505.5750,-1,140.0440,50.4275,29.2655,0,30,0,0,NaN
1767,1768,1,1,0.282353,0.552941,0.396078,0.000319,-1,0.036165,-1,...,-314.6830,-1,110.1630,78.2040,32.4988,0,30,0,0,NaN
1768,1769,1,1,0.341176,0.792157,0.454902,0.000434,-1,0.039702,-1,...,-302.5490,-1,94.9294,79.3552,42.2200,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.239216,0.086275,0.388235,0.030067,-1,0.829538,-1,...,-75.8312,-1,353.8130,123.6370,74.2475,5380,1722,0,0,NaN
1,2,1,0,0.749020,0.345098,0.023529,0.001373,-1,0.074487,-1,...,-55.0553,-1,74.8285,51.7754,27.8198,4992,85,0,0,NaN
2,3,1,0,0.788235,0.752941,0.490196,0.003825,-1,0.137609,-1,...,77.8601,-1,86.8976,73.8779,42.6225,4988,1255,0,0,NaN
3,4,1,0,0.011765,0.125490,0.486275,0.004621,-1,0.203895,-1,...,546.5680,-1,153.3340,62.6753,39.6390,4945,892,0,0,NaN
4,5,1,0,0.819608,0.525490,0.070588,0.024616,-1,0.621846,-1,...,-92.3165,-1,211.9960,142.8910,70.3877,4890,947,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1799,1800,1,1,0.478431,0.819608,0.619608,0.000157,-1,0.020725,-1,...,57.6156,-1,67.3710,59.0739,28.2677,0,30,0,0,NaN
1800,1801,1,1,0.733333,0.333333,0.376471,0.000276,-1,0.031753,-1,...,-339.4590,-1,106.2610,60.9685,29.4711,0,30,0,0,NaN
1801,1802,1,1,0.254902,0.054902,0.407843,0.000160,-1,0.018417,-1,...,-306.4350,-1,71.0612,59.4212,33.9366,0,30,0,0,NaN
1802,1803,1,1,0.125490,0.137255,0.192157,0.000435,-1,0.040801,-1,...,-513.7560,-1,109.1970,86.8568,37.5476,0,30,0,0,NaN
1803,1804,1,1,0.423529,0.666667,0.674510,0.000465,-1,0.040896,-1,...,-30.7821,-1,96.2500,82.8787,44.8740,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.784314,0.207843,0.125490,0.006453,-1,0.253858,-1,...,-275.1910,-1,94.7189,86.8532,49.0860,3850,179,0,0,NaN
1,2,1,0,0.909804,0.368627,0.615686,0.062155,-1,1.242370,-1,...,-81.1993,-1,343.6890,205.1270,115.8620,3401,302,0,0,NaN
2,3,1,0,0.301961,0.964706,0.101961,0.001111,-1,0.064391,-1,...,-398.9760,-1,72.0667,53.7837,26.6633,3344,1,0,0,NaN
3,4,1,0,0.992157,0.254902,0.682353,0.007593,-1,0.254315,-1,...,-255.8690,-1,106.4510,92.5630,71.0993,2667,253,0,0,NaN
4,5,1,0,0.776471,0.545098,0.235294,0.027172,-1,0.647512,-1,...,-241.1600,-1,268.0000,157.7810,100.3690,1842,42,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2291,2292,1,1,0.243137,0.796078,0.686275,0.000178,-1,0.022571,-1,...,174.9840,-1,89.4427,63.0390,32.4181,0,30,0,0,NaN
2292,2293,1,1,0.239216,0.298039,0.976471,0.000426,-1,0.037266,-1,...,76.6726,-1,101.3230,74.3148,43.5992,0,30,0,0,NaN
2293,2294,1,1,0.376471,0.843137,0.149020,0.000715,-1,0.049312,-1,...,-333.2220,-1,153.4440,90.9154,44.6330,1,30,0,0,NaN
2294,2295,1,1,0.745098,0.968627,0.584314,0.000176,-1,0.025814,-1,...,-370.1560,-1,89.1603,56.9517,24.4534,0,30,0,0,NaN
2295,2296,1,1,0.011765,0.690196,0.921569,0.000334,-1,0.033836,-1,...,-418.3830,-1,112.1760,66.6945,29.4695,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.011765,0.345098,0.235294,0.004432,-1,0.203272,-1,...,-125.4140,-1,77.7216,68.3608,46.9934,4979,2556,0,0,NaN
1,2,1,0,0.133333,0.458824,0.200000,0.036625,-1,0.769148,-1,...,-53.8219,-1,185.9420,171.5540,95.7722,3997,478,0,0,NaN
2,3,1,0,0.278431,0.447059,0.321569,0.025337,-1,0.568679,-1,...,-297.8760,-1,175.2450,172.2940,107.6430,1274,43,0,0,NaN
3,4,1,0,0.898039,0.800000,0.176471,0.030376,-1,0.674411,-1,...,-264.6270,-1,211.5380,198.4870,134.2930,1075,149,0,0,NaN
4,5,1,0,0.639216,0.247059,0.160784,0.006965,-1,0.270922,-1,...,376.7970,-1,225.4100,87.3829,59.7155,590,23,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4751,4752,1,1,0.607843,0.992157,0.811765,0.000206,-1,0.024962,-1,...,-438.7560,-1,90.5441,52.7334,33.2883,0,30,0,0,NaN
4752,4753,1,1,0.933333,0.321569,0.862745,0.000984,-1,0.058112,-1,...,-342.5950,-1,111.5240,100.0780,64.2941,0,30,0,0,NaN
4753,4754,1,1,0.647059,0.870588,0.031372,0.000350,-1,0.039196,-1,...,258.7660,-1,119.0400,74.6719,38.7061,0,30,0,0,NaN
4754,4755,1,1,0.996078,0.007843,0.592157,0.000280,-1,0.032111,-1,...,635.2390,-1,92.2957,64.3824,36.3642,0,30,0,0,NaN
4755,4756,1,1,0.917647,0.007843,0.847059,0.000353,-1,0.034255,-1,...,139.7360,-1,128.9650,66.7797,38.6226,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.301961,0.984314,0.368627,0.005239,-1,0.216468,-1,...,-248.0880,-1,88.6037,68.6198,41.0113,4961,430,0,0,NaN
1,2,1,0,0.090196,0.137255,0.996078,0.014512,-1,0.518176,-1,...,467.2390,-1,272.3330,85.2640,58.6380,4661,520,0,0,NaN
2,3,1,0,0.082353,0.352941,0.917647,0.006680,-1,0.250752,-1,...,-49.4984,-1,109.1770,91.2173,48.6858,2780,949,0,0,NaN
3,4,1,0,0.360784,0.435294,0.607843,0.034474,-1,0.672131,-1,...,-218.4920,-1,213.3110,205.7540,127.4070,1490,56,0,0,NaN
4,5,1,0,0.262745,0.239216,0.960784,0.008062,-1,0.306824,-1,...,-474.1560,-1,225.7030,86.9767,51.6190,893,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2300,2301,1,1,0.482353,0.250980,0.098039,0.000213,-1,0.027230,-1,...,179.3570,-1,132.0040,54.9225,27.1768,0,30,0,0,NaN
2301,2302,1,1,0.164706,0.501961,0.584314,0.000476,-1,0.043349,-1,...,428.5920,-1,110.5010,79.3329,39.7041,0,30,0,0,NaN
2302,2303,1,1,0.741176,0.552941,0.858824,0.000410,-1,0.042837,-1,...,-238.8530,-1,110.3890,73.2072,40.5168,0,30,0,0,NaN
2303,2304,1,1,0.352941,0.470588,0.541176,0.000130,-1,0.015268,-1,...,-245.4810,-1,53.6465,50.2751,31.8690,0,30,0,0,NaN
2304,2305,1,1,0.815686,0.698039,0.623529,0.000196,-1,0.023852,-1,...,-163.9540,-1,65.3929,63.4188,25.7674,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.003922,0.913725,0.337255,0.002333,-1,0.112243,-1,...,-11.3318,-1,94.1099,54.6484,34.0933,4989,2110,0,0,NaN
1,2,1,0,0.196078,0.682353,0.560784,0.004350,-1,0.225057,-1,...,-683.5290,-1,235.0150,65.6496,42.4550,3074,833,0,0,NaN
2,3,1,0,0.011765,0.094118,0.600000,0.011665,-1,0.353051,-1,...,-451.5340,-1,254.7000,114.3250,73.8727,619,0,0,0,NaN
3,4,1,0,0.211765,0.650980,0.713725,0.008838,-1,0.334287,-1,...,-443.6360,-1,293.0220,112.6870,72.8568,429,0,0,0,NaN
4,5,1,0,0.572549,0.101961,0.254902,0.016375,-1,0.415742,-1,...,-22.8524,-1,193.5590,176.7790,107.0380,418,31,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2506,2507,1,1,0.901961,0.035294,0.517647,0.000113,-1,0.021622,-1,...,-545.4070,-1,108.7630,49.7298,22.8444,0,30,0,0,NaN
2507,2508,1,1,0.180392,0.678431,0.407843,0.000124,-1,0.018643,-1,...,417.6270,-1,101.7690,41.6803,26.5912,0,30,0,0,NaN
2508,2509,1,1,0.172549,0.803922,0.309804,0.000836,-1,0.057701,-1,...,-146.8650,-1,132.9960,105.6100,64.3051,7,30,0,0,NaN
2509,2510,1,1,0.011765,0.462745,0.764706,0.000192,-1,0.020933,-1,...,-223.5350,-1,79.8296,56.1813,35.9412,0,30,0,0,NaN
2510,2511,1,1,0.415686,0.109804,0.925490,0.000418,-1,0.037034,-1,...,532.3940,-1,96.9420,94.4789,48.3001,0,24,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,0,1,-1,0.000000,0.000000,0.000000,-1.000000,-1,-1.000000,-1,...,0.0000,-1,0.000,0.0000,0.0000,0,0,0,0,NaN
1,1,1,0,0.592157,0.305882,0.717647,0.005122,-1,0.193973,-1,...,-41.4686,-1,82.612,77.1457,49.3670,4988,2947,0,0,NaN
2,2,1,0,0.494118,0.231373,0.384314,0.016334,-1,0.481763,-1,...,54.9889,-1,124.816,114.0060,70.0797,4860,2321,0,0,NaN
3,3,1,0,0.098039,0.654902,0.454902,0.016833,-1,0.532262,-1,...,348.7440,-1,322.995,100.4460,51.7686,4699,1299,0,0,NaN
4,4,1,0,0.423529,0.466667,0.650980,0.008716,-1,0.316631,-1,...,-388.7810,-1,229.519,89.4073,50.8667,4180,1637,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2040,2040,1,1,0.690196,0.121569,0.870588,0.000191,-1,0.026194,-1,...,385.6100,-1,124.294,53.8156,29.4666,1,30,0,0,NaN
2041,2041,1,1,0.870588,0.701961,0.313725,0.000251,-1,0.029699,-1,...,79.1237,-1,128.642,70.7945,29.8698,0,30,0,0,NaN
2042,2042,1,1,0.619608,0.768627,0.200000,0.000228,-1,0.026262,-1,...,357.1900,-1,131.857,57.8159,32.1898,0,30,0,0,NaN
2043,2043,1,1,0.341176,0.278431,0.933333,0.000692,-1,0.045465,-1,...,-335.9440,-1,115.290,91.9749,50.0537,1,30,0,0,NaN
2044,2044,1,1,0.007843,0.027451,0.643137,0.000265,-1,0.034133,-1,...,-619.9990,-1,126.069,66.1944,31.4560,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.384314,0.427451,0.129412,0.008563,-1,0.297145,-1,...,-43.3572,-1,101.252,83.0113,51.9650,4959,3265,0,0,NaN
1,2,1,0,0.647059,0.356863,0.537255,0.051875,-1,1.110830,-1,...,36.0372,-1,259.292,194.6240,115.9390,4137,708,0,0,NaN
2,3,1,0,0.317647,0.713725,0.470588,0.018336,-1,0.584429,-1,...,628.8530,-1,322.303,114.6270,68.6688,3473,971,0,0,NaN
3,4,1,0,0.396078,0.898039,0.337255,0.015299,-1,0.421657,-1,...,-320.8160,-1,121.598,111.4860,68.1954,3061,1338,0,0,NaN
4,5,1,0,0.537255,0.956863,0.866667,0.005627,-1,0.189698,-1,...,169.5850,-1,125.448,99.2943,58.4203,1124,758,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1972,1973,1,1,0.580392,0.533333,0.674510,0.000551,-1,0.047485,-1,...,-306.0790,-1,145.214,80.0071,48.7327,0,30,0,0,NaN
1973,1974,1,1,0.745098,0.694118,0.113725,0.000527,-1,0.044324,-1,...,-303.7350,-1,123.218,95.9523,42.1676,0,30,0,0,NaN
1974,1975,1,1,0.807843,0.039216,0.984314,0.000305,-1,0.035854,-1,...,655.9050,-1,117.349,75.4642,31.8245,0,30,0,0,NaN
1975,1976,1,1,0.121569,0.219608,0.372549,0.000414,-1,0.043250,-1,...,418.9370,-1,140.840,76.2730,34.2498,0,30,0,0,NaN
1976,1977,1,1,0.690196,0.000000,0.164706,0.000188,-1,0.022875,-1,...,-86.1144,-1,72.233,58.8244,30.5355,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.658824,0.090196,0.027451,0.003641,-1,0.152927,-1,...,-131.2760,-1,91.4332,65.6533,38.9206,4982,507,0,0,NaN
1,2,1,0,0.858824,0.000000,0.513725,0.010540,-1,0.330510,-1,...,70.6121,-1,124.5050,91.1400,52.5754,4925,1213,0,0,NaN
2,3,1,0,0.933333,0.435294,0.556863,0.015463,-1,0.435085,-1,...,-228.7110,-1,178.9870,112.5100,75.0257,4890,1247,0,0,NaN
3,4,1,0,0.968627,0.643137,0.098039,0.013972,-1,0.435581,-1,...,110.6200,-1,137.2300,104.7010,56.3107,4458,602,0,0,NaN
4,5,1,0,0.611765,0.701961,0.960784,0.018385,-1,0.542692,-1,...,591.1570,-1,258.4780,104.2260,69.8117,4200,666,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993,2994,1,1,0.835294,0.823529,0.427451,0.000169,-1,0.029096,-1,...,248.0970,-1,101.8660,54.1420,27.9311,0,30,0,0,NaN
2994,2995,1,1,0.980392,0.070588,0.996078,0.000510,-1,0.043697,-1,...,343.7020,-1,120.1760,83.9158,46.4050,0,30,0,0,NaN
2995,2996,1,1,0.376471,0.596078,0.015686,0.000669,-1,0.048106,-1,...,-287.6660,-1,110.6390,96.2505,59.8481,1,30,0,0,NaN
2996,2997,1,1,0.313725,0.654902,0.807843,0.000159,-1,0.018594,-1,...,-59.6101,-1,70.4997,54.0690,25.7508,0,30,0,0,NaN
2997,2998,1,1,0.262745,0.509804,1.000000,0.000329,-1,0.029413,-1,...,-312.0850,-1,76.7172,73.6989,49.6314,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.600000,0.258824,0.137255,0.006568,-1,0.242127,-1,...,-153.2180,-1,99.4903,86.8169,53.1447,4997,1765,0,0,NaN
1,2,1,0,0.517647,0.819608,0.960784,0.007527,-1,0.237552,-1,...,-39.2401,-1,91.5100,91.0227,57.9973,4923,2625,0,0,NaN
2,3,1,0,0.705882,0.113725,0.254902,0.008677,-1,0.368050,-1,...,419.6860,-1,534.3490,89.3976,39.9772,4793,662,0,0,NaN
3,4,1,0,0.721569,0.247059,0.254902,0.019888,-1,0.658898,-1,...,-266.9660,-1,418.1500,96.2230,53.7705,4557,3664,0,0,NaN
4,5,1,0,0.607843,0.356863,0.313725,0.030743,-1,0.747883,-1,...,-220.3410,-1,269.4640,119.1740,79.8534,4009,1426,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1103,1104,1,1,0.592157,0.019608,0.454902,0.000613,-1,0.051982,-1,...,126.4780,-1,117.9260,105.4740,50.9445,0,30,0,0,NaN
1104,1105,1,1,0.756863,0.313725,0.349020,0.000360,-1,0.032498,-1,...,-103.3110,-1,91.9345,74.9125,42.7085,0,30,0,0,NaN
1105,1106,1,1,0.635294,0.898039,0.556863,0.000948,-1,0.059339,-1,...,-349.9040,-1,144.9100,100.7980,59.3072,0,30,0,0,NaN
1106,1107,1,1,0.674510,0.545098,0.741176,0.000479,-1,0.037853,-1,...,702.7050,-1,113.4850,89.0374,59.4539,0,30,0,0,NaN
1107,1108,1,1,0.482353,0.286275,0.470588,0.000185,-1,0.030748,-1,...,190.6410,-1,94.5038,71.0304,42.3167,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.870588,0.698039,0.529412,0.010971,-1,0.353777,-1,...,-371.4930,-1,219.9350,116.8290,77.2433,473,0,0,0,NaN
1,2,1,0,0.807843,0.341176,0.054902,0.031363,-1,0.703764,-1,...,-185.8480,-1,414.0760,231.4170,121.6690,395,4,0,0,NaN
2,3,1,0,0.101961,0.188235,0.411765,0.010618,-1,0.291589,-1,...,639.7810,-1,196.0940,149.6200,101.3630,391,1,0,0,NaN
3,4,1,0,0.129412,0.850980,0.407843,0.008517,-1,0.360722,-1,...,356.2350,-1,349.2880,99.0678,67.6341,384,0,0,0,NaN
4,5,1,0,0.227451,0.266667,0.678431,0.002004,-1,0.116531,-1,...,265.3920,-1,138.3300,57.0379,37.1211,381,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1011,1012,1,1,0.894118,0.470588,0.019608,0.000441,-1,0.042036,-1,...,-107.0630,-1,95.5111,76.7253,49.3466,0,30,0,0,NaN
1012,1013,1,1,0.705882,0.796078,0.470588,0.000809,-1,0.048920,-1,...,-163.4580,-1,117.4740,97.9493,58.2755,0,30,0,0,NaN
1013,1014,1,1,0.925490,0.764706,0.447059,0.000203,-1,0.022494,-1,...,-116.2260,-1,75.9364,63.6338,36.1911,0,30,0,0,NaN
1014,1015,1,1,0.411765,0.137255,0.466667,0.000518,-1,0.041063,-1,...,-28.7253,-1,145.5890,77.1418,45.4998,0,30,0,0,NaN
1015,1016,1,1,0.341176,0.854902,0.596078,0.000642,-1,0.048305,-1,...,-85.4062,-1,110.7660,92.4341,52.7070,0,29,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.619608,0.886275,0.894118,0.010560,-1,0.401059,-1,...,600.5840,-1,239.7120,89.2463,57.7545,4634,601,0,0,NaN
1,2,1,0,0.615686,0.454902,0.215686,0.010419,-1,0.313757,-1,...,-557.4770,-1,149.1320,99.3167,60.6996,1573,0,0,0,NaN
2,3,1,0,0.462745,0.776471,0.160784,0.023623,-1,0.642175,-1,...,610.7800,-1,425.4340,146.1770,87.6824,1204,12,0,0,NaN
3,4,1,0,0.956863,0.929412,0.615686,0.009537,-1,0.325574,-1,...,593.2390,-1,161.2410,118.0430,61.4776,863,1,0,0,NaN
4,5,1,0,0.905882,0.917647,0.780392,0.006923,-1,0.261199,-1,...,-237.6880,-1,132.0180,91.7738,58.9036,765,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3786,3787,1,1,0.270588,0.207843,0.039216,0.000252,-1,0.028007,-1,...,-38.7805,-1,80.0838,61.1351,34.7345,0,30,0,0,NaN
3787,3788,1,1,0.682353,0.321569,0.239216,0.000158,-1,0.022201,-1,...,-29.8172,-1,75.8359,49.9965,31.1194,0,30,0,0,NaN
3788,3789,1,1,0.400000,0.996078,0.105882,0.000387,-1,0.036231,-1,...,-437.9410,-1,116.2580,64.9889,34.2595,0,30,0,0,NaN
3789,3790,1,1,0.305882,0.988235,0.388235,0.000848,-1,0.052447,-1,...,676.9740,-1,114.0470,93.3768,61.1096,0,30,0,0,NaN
3790,3791,1,1,0.780392,0.372549,0.149020,0.000444,-1,0.036502,-1,...,-50.1465,-1,106.5450,80.7834,50.6817,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.980392,0.509804,0.615686,0.004173,-1,0.203549,-1,...,-106.1570,-1,97.3069,69.4168,35.0321,4985,351,0,0,NaN
1,2,1,0,0.886275,0.094118,0.356863,0.018154,-1,0.500870,-1,...,-227.5330,-1,107.0450,106.4040,69.6348,4684,3806,0,0,NaN
2,3,1,0,0.937255,0.901961,0.200000,0.034998,-1,0.841461,-1,...,196.2220,-1,362.6970,147.2580,74.1405,4252,381,0,0,NaN
3,4,1,0,0.709804,0.466667,0.941176,0.025828,-1,0.604016,-1,...,19.1993,-1,167.3400,138.3320,93.4358,3489,187,0,0,NaN
4,5,1,0,0.482353,0.596078,0.654902,0.012665,-1,0.355420,-1,...,-65.0062,-1,142.9240,103.6830,71.1256,2958,21,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2376,2377,1,1,0.392157,0.611765,0.607843,0.000317,-1,0.029870,-1,...,-138.9070,-1,81.1441,69.7722,46.9376,0,30,0,0,NaN
2377,2378,1,1,0.458824,0.525490,0.007843,0.000306,-1,0.033080,-1,...,609.0310,-1,126.9240,82.5507,39.8975,0,30,0,0,NaN
2378,2379,1,1,0.321569,0.615686,0.866667,0.000331,-1,0.030536,-1,...,-119.9920,-1,80.8447,65.6360,38.2211,0,30,0,0,NaN
2379,2380,1,1,0.564706,0.752941,0.913725,0.000351,-1,0.033264,-1,...,-410.0640,-1,97.7376,75.1410,47.3540,0,30,0,0,NaN
2380,2381,1,1,0.376471,0.737255,0.686275,0.000062,-1,0.015309,-1,...,309.6140,-1,84.1159,35.4353,13.9346,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.968627,0.333333,0.192157,0.023137,-1,0.665288,-1,...,515.4300,-1,355.4320,104.5200,68.9211,4712,1119,0,0,NaN
1,2,1,0,0.270588,0.388235,0.984314,0.012956,-1,0.409242,-1,...,-213.2750,-1,162.7900,114.7250,71.7920,1739,2033,0,0,NaN
2,3,1,0,0.600000,0.764706,0.725490,0.033613,-1,0.632651,-1,...,-214.3880,-1,190.2570,170.0540,124.7090,1517,200,0,0,NaN
3,4,1,0,0.309804,0.462745,0.917647,0.008249,-1,0.294938,-1,...,146.7980,-1,213.6880,100.8610,62.1001,640,0,0,0,NaN
4,5,1,0,0.360784,0.435294,0.184314,0.006049,-1,0.235582,-1,...,103.2790,-1,168.3980,94.9115,60.9421,493,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1764,1765,1,1,0.596078,0.109804,0.470588,0.000273,-1,0.028100,-1,...,40.8072,-1,120.0030,63.3803,40.6883,0,30,0,0,NaN
1765,1766,1,1,0.658824,0.250980,0.776471,0.000528,-1,0.040635,-1,...,-311.4120,-1,113.2100,78.9770,44.1100,0,30,0,0,NaN
1766,1767,1,1,0.749020,0.282353,0.568627,0.000236,-1,0.028752,-1,...,-581.0350,-1,92.8260,56.7384,36.9195,0,30,0,0,NaN
1767,1768,1,1,0.635294,0.411765,0.058824,0.000198,-1,0.022455,-1,...,-30.5012,-1,82.0854,55.0441,36.2386,0,30,0,0,NaN
1768,1769,1,1,1.000000,0.556863,0.752941,0.000306,-1,0.030985,-1,...,-575.0080,-1,117.3460,61.2630,39.0046,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.792157,0.705882,0.462745,0.002859,-1,0.128765,-1,...,85.7392,-1,78.2248,59.1244,37.8907,4971,2289,0,0,NaN
1,2,1,0,0.345098,0.035294,0.172549,0.004748,-1,0.199104,-1,...,617.0710,-1,127.4030,67.7950,43.7364,4780,1984,0,0,NaN
2,3,1,0,0.266667,0.266667,0.521569,0.003321,-1,0.156606,-1,...,-309.9690,-1,69.0232,66.7833,34.3975,4380,1542,0,0,NaN
3,4,1,0,0.117647,0.639216,0.109804,0.021804,-1,0.499684,-1,...,-110.2890,-1,123.5850,122.8050,76.3480,4332,1631,0,0,NaN
4,5,1,0,0.933333,0.682353,0.764706,0.008710,-1,0.274496,-1,...,-292.0740,-1,108.4180,93.6817,60.1580,3875,728,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3079,3080,1,1,0.501961,0.341176,0.647059,0.000307,-1,0.035375,-1,...,-570.6450,-1,115.1720,68.3100,29.1394,0,30,0,0,NaN
3080,3081,1,1,0.819608,0.435294,0.850980,0.000157,-1,0.021955,-1,...,472.9230,-1,107.2260,48.7356,24.7882,0,30,0,0,NaN
3081,3082,1,1,0.533333,0.466667,0.270588,0.000345,-1,0.031488,-1,...,-142.9540,-1,76.8608,67.9472,38.2979,0,30,0,0,NaN
3082,3083,1,1,0.439216,0.890196,0.541176,0.000281,-1,0.033136,-1,...,472.5230,-1,128.7300,88.6549,33.0962,0,30,0,0,NaN
3083,3084,1,1,0.874510,0.474510,0.262745,0.000308,-1,0.030626,-1,...,-617.4840,-1,110.1400,68.6128,41.2323,1,23,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.101961,0.400000,0.815686,0.007860,-1,0.323143,-1,...,-341.1750,-1,142.4360,85.1878,50.5819,1602,0,0,0,NaN
1,2,1,0,0.466667,0.254902,0.341176,0.008102,-1,0.256922,-1,...,-399.5020,-1,119.8530,101.9110,81.8986,589,0,0,0,NaN
2,3,1,0,0.121569,0.713725,0.290196,0.016857,-1,0.444619,-1,...,-44.6454,-1,199.8340,153.1820,98.2600,580,0,0,0,NaN
3,4,1,0,0.231373,0.698039,0.180392,0.014011,-1,0.409381,-1,...,52.0574,-1,236.4420,138.8100,95.1713,553,0,0,0,NaN
4,5,1,0,0.145098,0.752941,0.243137,0.003799,-1,0.171170,-1,...,98.9670,-1,114.2690,71.9942,43.6354,549,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4463,4464,1,1,0.819608,0.627451,0.678431,0.000128,-1,0.018496,-1,...,-73.0334,-1,90.5248,45.9746,24.5946,0,30,0,0,NaN
4464,4465,1,1,0.086275,0.764706,0.172549,0.000067,-1,0.016212,-1,...,-418.3470,-1,123.3740,38.9946,19.9200,0,30,0,0,NaN
4465,4466,1,1,0.019608,0.776471,0.737255,0.000219,-1,0.031263,-1,...,-344.7780,-1,100.5430,57.1692,28.8606,0,30,0,0,NaN
4466,4467,1,1,0.607843,0.043137,0.443137,0.000060,-1,0.014136,-1,...,142.9350,-1,84.0775,36.3814,17.3272,0,30,0,0,NaN
4467,4468,1,1,0.403922,0.196078,0.694118,0.000578,-1,0.046904,-1,...,-104.4000,-1,122.5670,92.7978,48.6200,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.078431,0.815686,0.992157,0.004024,-1,0.182624,-1,...,-284.2420,-1,72.3401,67.4279,46.1820,4872,351,0,0,NaN
1,2,1,0,0.282353,0.945098,0.603922,0.008475,-1,0.297077,-1,...,-254.2560,-1,118.7090,102.3820,80.7485,4860,430,0,0,NaN
2,3,1,0,0.062745,0.768627,0.545098,0.048357,-1,0.978128,-1,...,-234.5710,-1,380.8140,170.8250,108.8780,2638,452,0,0,NaN
3,4,1,0,0.141176,0.301961,0.082353,0.010874,-1,0.309425,-1,...,-233.0100,-1,124.4960,102.6480,66.7842,1018,1,0,0,NaN
4,5,1,0,0.180392,0.713725,0.431373,0.027494,-1,0.583487,-1,...,-261.8000,-1,196.5210,177.9850,123.0750,952,90,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4353,4354,1,1,0.141176,0.611765,0.933333,0.000319,-1,0.034186,-1,...,-422.3230,-1,123.7670,69.5222,34.0926,0,30,0,0,NaN
4354,4355,1,1,0.388235,0.074510,0.886275,0.000577,-1,0.044580,-1,...,-282.2500,-1,118.4670,102.7140,58.1644,0,30,0,0,NaN
4355,4356,1,1,0.321569,0.384314,0.886275,0.000198,-1,0.023646,-1,...,168.2620,-1,89.6178,51.2752,33.7593,0,30,0,0,NaN
4356,4357,1,1,0.772549,0.580392,0.647059,0.000181,-1,0.026245,-1,...,32.5617,-1,102.2330,57.6888,38.3501,0,30,0,0,NaN
4357,4358,1,1,0.549020,0.686275,0.796078,0.000622,-1,0.055773,-1,...,388.5270,-1,119.8970,113.5670,53.6287,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.239216,0.894118,0.505882,0.001962,-1,0.096743,-1,...,-106.1070,-1,61.2475,57.0885,33.1856,4981,270,0,0,NaN
1,2,1,0,0.533333,0.278431,0.098039,0.005872,-1,0.283599,-1,...,452.4680,-1,260.9480,64.1846,33.4349,4932,694,0,0,NaN
2,3,1,0,0.584314,0.141176,0.443137,0.005711,-1,0.209053,-1,...,130.5240,-1,107.5620,81.3857,40.0295,4913,344,0,0,NaN
3,4,1,0,0.470588,0.843137,0.505882,0.011223,-1,0.376065,-1,...,-141.5970,-1,103.3110,92.6880,62.5945,4832,1195,0,0,NaN
4,5,1,0,0.447059,0.172549,0.274510,0.010769,-1,0.341243,-1,...,27.5428,-1,103.8030,97.0697,60.2161,4821,1409,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5360,5361,1,1,0.360784,0.152941,0.470588,0.000454,-1,0.042224,-1,...,-357.9070,-1,129.2040,82.4008,51.8234,0,30,0,0,NaN
5361,5362,1,1,0.788235,0.062745,0.074510,0.000191,-1,0.021635,-1,...,-144.8200,-1,67.3786,64.1712,39.2698,0,30,0,0,NaN
5362,5363,1,1,0.560784,0.364706,0.894118,0.000921,-1,0.056424,-1,...,-347.4760,-1,120.4720,103.0330,61.4989,0,30,0,0,NaN
5363,5364,1,1,0.211765,0.086275,0.352941,0.000223,-1,0.026218,-1,...,-391.0110,-1,120.1850,59.2993,28.4036,0,30,0,0,NaN
5364,5365,1,1,0.882353,0.027451,0.392157,0.000220,-1,0.024728,-1,...,-376.1790,-1,103.1100,59.5427,39.4945,0,25,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.741176,0.937255,0.800000,0.003478,-1,0.144662,-1,...,-266.5060,-1,68.6668,68.2199,46.8464,4974,283,0,0,NaN
1,2,1,0,0.164706,0.223529,0.043137,0.003028,-1,0.129195,-1,...,-251.9940,-1,73.5779,56.2878,36.8860,4964,3,0,0,NaN
2,3,1,0,0.313725,0.474510,0.807843,0.007302,-1,0.291584,-1,...,-27.6346,-1,82.5506,77.7706,52.3039,4944,1030,0,0,NaN
3,4,1,0,0.952941,0.721569,0.568627,0.004473,-1,0.184279,-1,...,-318.0980,-1,73.8277,73.2327,48.8260,4910,151,0,0,NaN
4,5,1,0,0.576471,0.035294,0.909804,0.001043,-1,0.067870,-1,...,-206.9300,-1,51.0506,47.1302,24.7207,4888,204,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3635,3636,1,1,0.807843,0.501961,0.905882,0.000255,-1,0.029375,-1,...,-388.4160,-1,109.2830,57.5205,32.3778,0,30,0,0,NaN
3636,3637,1,1,0.447059,0.984314,0.082353,0.000908,-1,0.059948,-1,...,-387.1240,-1,135.0820,116.4080,54.1187,0,30,0,0,NaN
3637,3638,1,1,0.533333,0.600000,0.341176,0.000083,-1,0.014060,-1,...,-287.6870,-1,85.2339,38.8982,22.7412,0,30,0,0,NaN
3638,3639,1,1,0.094118,0.980392,0.713725,0.000325,-1,0.032222,-1,...,63.7857,-1,141.5070,69.2469,41.3686,0,30,0,0,NaN
3639,3640,1,1,0.964706,0.388235,0.337255,0.000679,-1,0.051511,-1,...,-314.2460,-1,112.2950,86.5835,47.2830,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.031372,0.854902,0.752941,0.008540,-1,0.340439,-1,...,259.4090,-1,182.6030,76.5393,45.9302,2549,0,0,0,NaN
1,2,1,0,0.043137,0.074510,0.729412,0.043787,-1,0.957654,-1,...,-258.0820,-1,366.7990,224.4150,137.1810,1319,24,0,0,NaN
2,3,1,0,0.552941,0.898039,0.388235,0.037133,-1,0.807947,-1,...,-130.7110,-1,377.9050,220.0410,134.9820,826,37,0,0,NaN
3,4,1,0,0.470588,0.003922,0.454902,0.008656,-1,0.317241,-1,...,142.8040,-1,231.4150,100.8330,69.0860,729,0,0,0,NaN
4,5,1,0,0.250980,0.121569,0.901961,0.030939,-1,0.661044,-1,...,-196.7530,-1,263.4000,253.9920,137.1380,605,14,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2435,2436,1,1,0.011765,0.333333,0.917647,0.000281,-1,0.029043,-1,...,603.0740,-1,115.4920,58.2237,35.4327,0,30,0,0,NaN
2436,2437,1,1,0.894118,0.772549,0.203922,0.000124,-1,0.020031,-1,...,-40.5443,-1,77.7569,55.9236,36.9361,0,30,0,0,NaN
2437,2438,1,1,0.878431,0.443137,0.215686,0.000919,-1,0.057192,-1,...,-180.1750,-1,119.7350,105.6680,60.5817,0,30,0,0,NaN
2438,2439,1,1,0.611765,0.650980,0.454902,0.000275,-1,0.026385,-1,...,-75.9820,-1,75.2560,65.3333,40.1212,0,30,0,0,NaN
2439,2440,1,1,0.643137,0.262745,0.011765,0.000264,-1,0.025902,-1,...,229.9040,-1,87.2829,83.0888,36.7378,0,20,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.529412,0.129412,0.803922,0.006506,-1,0.300291,-1,...,446.5300,-1,243.6990,63.4165,38.6629,4914,1313,0,0,NaN
1,2,1,0,0.396078,0.909804,0.109804,0.040490,-1,0.815904,-1,...,122.1810,-1,251.2450,226.1410,146.2490,1539,690,0,0,NaN
2,3,1,0,0.125490,0.274510,0.192157,0.009822,-1,0.354015,-1,...,-463.2420,-1,293.4730,111.7170,68.6785,706,0,0,0,NaN
3,4,1,0,0.752941,0.788235,0.717647,0.004831,-1,0.196343,-1,...,-69.6687,-1,139.3160,81.0182,51.8023,640,0,0,0,NaN
4,5,1,0,0.784314,0.741176,0.192157,0.023780,-1,0.526674,-1,...,-182.9390,-1,223.9090,205.2240,110.8740,627,14,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844,2845,1,1,0.666667,0.709804,0.070588,0.000091,-1,0.015559,-1,...,-293.1680,-1,73.7388,44.0533,21.4062,0,30,0,0,NaN
2845,2846,1,1,0.352941,0.250980,0.400000,0.000244,-1,0.028697,-1,...,-382.9150,-1,107.3940,73.7329,32.0829,0,30,0,0,NaN
2846,2847,1,1,0.490196,0.960784,0.623529,0.000163,-1,0.021678,-1,...,-609.1930,-1,126.9960,47.2647,31.2380,0,30,0,0,NaN
2847,2848,1,1,0.000000,0.725490,0.854902,0.000085,-1,0.010894,-1,...,-197.1110,-1,46.7784,45.4985,30.3522,0,30,0,0,NaN
2848,2849,1,1,0.298039,0.545098,0.482353,0.000259,-1,0.028271,-1,...,-139.1850,-1,92.0500,54.4631,35.1355,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.109804,0.521569,0.180392,0.002159,-1,0.105932,-1,...,-40.765100,-1,72.9139,50.9419,31.5834,4981,568,0,0,NaN
1,2,1,0,0.270588,0.231373,0.376471,0.007645,-1,0.369776,-1,...,386.178000,-1,267.4810,62.8716,36.8952,4974,1369,0,0,NaN
2,3,1,0,0.360784,0.717647,0.843137,0.001254,-1,0.067432,-1,...,-89.940800,-1,64.5970,52.3116,33.4800,4881,30,0,0,NaN
3,4,1,0,0.721569,0.203922,0.862745,0.020346,-1,0.500375,-1,...,-57.225000,-1,145.8970,119.0070,80.6094,3767,84,0,0,NaN
4,5,1,0,0.949020,0.462745,0.160784,0.013805,-1,0.375156,-1,...,-0.044336,-1,160.7380,113.6790,74.1522,2100,116,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3486,3487,1,1,0.443137,0.921569,0.325490,0.000079,-1,0.016533,-1,...,-476.414000,-1,99.2748,33.2522,19.3062,0,30,0,0,NaN
3487,3488,1,1,0.023529,0.862745,0.466667,0.000149,-1,0.018711,-1,...,-100.609000,-1,57.3854,55.3571,39.7316,0,30,0,0,NaN
3488,3489,1,1,0.588235,0.709804,0.427451,0.000109,-1,0.018523,-1,...,-451.244000,-1,121.1640,40.4516,21.8640,0,30,0,0,NaN
3489,3490,1,1,0.129412,0.019608,0.807843,0.000403,-1,0.040872,-1,...,-195.892000,-1,113.0090,89.5573,41.9888,0,30,0,0,NaN
3490,3491,1,1,0.937255,0.325490,0.964706,0.000088,-1,0.014397,-1,...,-369.597000,-1,124.5630,38.6575,26.2719,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.180392,0.796078,0.854902,0.002415,-1,0.107852,-1,...,45.07330,-1,77.9655,69.2682,38.6981,4996,886,0,0,NaN
1,2,1,0,0.670588,0.447059,0.745098,0.012159,-1,0.353676,-1,...,-242.18500,-1,115.3820,108.8080,71.1470,4604,1300,0,0,NaN
2,3,1,0,0.301961,0.058824,0.501961,0.017753,-1,0.402410,-1,...,-259.23000,-1,129.6300,116.3190,80.4699,4474,1901,0,0,NaN
3,4,1,0,0.015686,0.819608,0.211765,0.014743,-1,0.440748,-1,...,80.64350,-1,194.2420,134.8890,62.5258,4463,1048,0,0,NaN
4,5,1,0,0.666667,0.349020,0.639216,0.003574,-1,0.180023,-1,...,7.37488,-1,204.2060,68.0518,42.2882,1107,370,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1101,1102,1,1,0.725490,0.831373,0.988235,0.000752,-1,0.048266,-1,...,-87.02510,-1,113.7050,100.2440,62.7329,0,30,0,0,NaN
1102,1103,1,1,0.152941,0.215686,0.152941,0.000243,-1,0.031027,-1,...,8.00949,-1,135.1380,68.6463,31.1069,0,30,0,0,NaN
1103,1104,1,1,0.701961,0.964706,0.258824,0.000164,-1,0.023524,-1,...,244.30900,-1,95.7531,58.3815,24.1731,0,30,0,0,NaN
1104,1105,1,1,0.388235,0.352941,0.368627,0.000119,-1,0.017336,-1,...,481.39800,-1,82.5770,48.2185,20.8949,0,30,0,0,NaN
1105,1106,1,1,0.776471,0.007843,0.682353,0.000556,-1,0.044364,-1,...,-300.54400,-1,117.7670,88.0448,46.2248,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.972549,0.996078,0.152941,0.006774,-1,0.244036,-1,...,-328.5890,-1,96.2046,87.2128,58.2209,4794,1363,0,0,NaN
1,2,1,0,0.839216,0.113725,0.741176,0.003756,-1,0.173506,-1,...,-34.6827,-1,143.9560,61.4837,40.7239,4084,104,0,0,NaN
2,3,1,0,0.243137,0.505882,0.435294,0.001563,-1,0.082841,-1,...,78.1859,-1,87.2863,58.1400,34.3937,3396,8,0,0,NaN
3,4,1,0,0.188235,0.270588,0.188235,0.006737,-1,0.232347,-1,...,669.7890,-1,136.1550,96.2028,58.3157,3343,113,0,0,NaN
4,5,1,0,0.321569,0.129412,0.247059,0.008937,-1,0.282584,-1,...,-297.3640,-1,110.6630,98.1956,72.7812,3073,1459,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4738,4739,1,1,0.282353,0.650980,0.282353,0.000234,-1,0.025794,-1,...,-375.7020,-1,125.2980,48.1897,31.9275,0,30,0,0,NaN
4739,4740,1,1,0.643137,0.419608,0.188235,0.000560,-1,0.047184,-1,...,-287.5430,-1,131.0400,95.2783,47.6429,1,30,0,0,NaN
4740,4741,1,1,0.976471,0.003922,0.482353,0.000363,-1,0.038048,-1,...,-421.2870,-1,135.6040,71.9993,29.0863,0,30,0,0,NaN
4741,4742,1,1,0.549020,0.611765,0.345098,0.000343,-1,0.037220,-1,...,-307.3950,-1,128.8570,74.1743,35.0456,0,30,0,0,NaN
4742,4743,1,1,0.243137,0.482353,0.784314,0.000101,-1,0.019775,-1,...,141.0140,-1,95.1654,56.5429,18.5169,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.545098,0.152941,0.917647,0.006540,-1,0.243402,-1,...,92.9482,-1,115.8130,86.5201,47.7629,4960,648,0,0,NaN
1,2,1,0,0.866667,0.003922,0.498039,0.018035,-1,0.572940,-1,...,645.9130,-1,300.4610,114.0980,62.7357,3790,201,0,0,NaN
2,3,1,0,0.894118,0.988235,0.309804,0.028700,-1,0.594597,-1,...,-262.2960,-1,159.5830,157.1970,110.5690,2488,826,0,0,NaN
3,4,1,0,0.345098,0.521569,0.494118,0.015500,-1,0.403084,-1,...,126.3400,-1,141.8400,134.7100,87.8236,2234,223,0,0,NaN
4,5,1,0,0.811765,0.709804,0.113725,0.029245,-1,0.646680,-1,...,-170.0810,-1,182.7960,166.7120,113.3460,2041,347,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1707,1708,1,1,0.113725,0.262745,0.384314,0.000291,-1,0.028842,-1,...,-12.5062,-1,127.7430,54.6000,33.3610,0,30,0,0,NaN
1708,1709,1,1,0.403922,0.890196,0.050980,0.000695,-1,0.049700,-1,...,-232.5530,-1,106.8420,102.5800,45.7575,0,30,0,0,NaN
1709,1710,1,1,0.541176,0.239216,0.380392,0.000283,-1,0.029731,-1,...,62.8466,-1,96.7287,62.4718,33.8473,0,30,0,0,NaN
1710,1711,1,1,0.662745,0.619608,0.615686,0.000464,-1,0.041031,-1,...,-128.9340,-1,82.4035,75.5096,50.8259,0,30,0,0,NaN
1711,1712,1,1,0.764706,0.411765,0.039216,0.000525,-1,0.045173,-1,...,-346.1360,-1,138.6660,92.7585,42.4633,1,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.960784,0.203922,0.435294,0.018366,-1,0.451433,-1,...,-316.33900,-1,143.2330,127.9800,81.1950,3271,1165,0,0,NaN
1,2,1,0,0.925490,0.215686,0.349020,0.023712,-1,0.635733,-1,...,196.45800,-1,305.9920,134.2350,80.2433,1550,82,0,0,NaN
2,3,1,0,0.764706,0.203922,0.349020,0.017869,-1,0.434502,-1,...,-157.21800,-1,165.0710,140.7970,99.2557,734,0,0,0,NaN
3,4,1,0,0.941176,0.384314,0.078431,0.036221,-1,0.785603,-1,...,-227.97800,-1,331.1240,231.8470,154.4090,632,34,0,0,NaN
4,5,1,0,0.996078,0.278431,0.098039,0.005360,-1,0.215863,-1,...,-301.28900,-1,117.3810,114.6890,59.3348,318,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877,1878,1,1,0.690196,0.109804,0.623529,0.000402,-1,0.035048,-1,...,-105.68100,-1,90.5810,88.4635,45.0295,0,30,0,0,NaN
1878,1879,1,1,0.603922,0.243137,0.380392,0.000464,-1,0.038772,-1,...,496.68800,-1,105.2290,85.1608,37.6920,0,30,0,0,NaN
1879,1880,1,1,0.419608,0.458824,0.423529,0.000539,-1,0.040380,-1,...,1.06907,-1,95.7277,90.6537,51.3887,0,30,0,0,NaN
1880,1881,1,1,0.129412,0.109804,0.878431,0.000337,-1,0.035927,-1,...,-314.77100,-1,140.3440,78.0221,36.3938,0,30,0,0,NaN
1881,1882,1,1,0.176471,0.627451,0.596078,0.000609,-1,0.045538,-1,...,-44.45520,-1,91.4919,90.5353,52.7295,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.050980,0.176471,0.545098,0.009282,-1,0.313182,-1,...,-330.4460,-1,114.4920,100.2200,54.5043,4366,2376,0,0,NaN
1,2,1,0,0.090196,0.478431,0.952941,0.029812,-1,0.606570,-1,...,-133.1780,-1,178.7860,168.6170,112.4470,1576,94,0,0,NaN
2,3,1,0,0.937255,0.478431,0.039216,0.018866,-1,0.571351,-1,...,250.7070,-1,344.8970,117.2990,75.9035,1108,0,0,0,NaN
3,4,1,0,0.290196,0.427451,0.274510,0.008907,-1,0.385050,-1,...,300.2820,-1,347.5760,98.9536,61.9760,562,0,0,0,NaN
4,5,1,0,0.941176,0.556863,0.125490,0.006451,-1,0.250811,-1,...,90.5131,-1,168.0130,99.5061,63.1367,510,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4170,4171,1,1,0.992157,0.478431,0.964706,0.000238,-1,0.031722,-1,...,134.5840,-1,101.5390,67.1767,26.8652,0,30,0,0,NaN
4171,4172,1,1,0.945098,0.780392,0.494118,0.000577,-1,0.044292,-1,...,-304.3160,-1,97.0024,81.4303,43.0591,0,30,0,0,NaN
4172,4173,1,1,0.772549,0.470588,0.568627,0.000543,-1,0.044872,-1,...,-112.1400,-1,119.6000,89.6335,43.3081,0,30,0,0,NaN
4173,4174,1,1,0.427451,0.525490,0.286275,0.000444,-1,0.041844,-1,...,-323.8640,-1,129.1870,68.4997,47.1989,0,30,0,0,NaN
4174,4175,1,1,0.149020,0.525490,0.713725,0.000589,-1,0.043802,-1,...,-154.4440,-1,90.7888,89.6951,51.4520,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.133333,0.937255,0.023529,0.006038,-1,0.235244,-1,...,-326.34100,-1,80.5501,73.4194,47.7794,4926,1546,0,0,NaN
1,2,1,0,0.247059,0.341176,0.454902,0.005888,-1,0.237812,-1,...,-332.31800,-1,126.2140,77.0148,40.3519,4825,927,0,0,NaN
2,3,1,0,0.078431,0.886275,0.552941,0.004664,-1,0.184918,-1,...,-321.26800,-1,80.7300,80.3576,48.9922,4711,1756,0,0,NaN
3,4,1,0,0.741176,0.568627,0.478431,0.010752,-1,0.365020,-1,...,-291.78000,-1,95.7077,86.3345,50.3909,4710,3323,0,0,NaN
4,5,1,0,0.309804,0.078431,0.674510,0.022660,-1,0.561665,-1,...,-289.19000,-1,157.4830,139.6930,74.5068,2751,1166,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3518,3519,1,1,0.866667,0.349020,0.619608,0.000096,-1,0.014460,-1,...,190.39600,-1,81.3924,48.3742,32.2740,0,30,0,0,NaN
3519,3520,1,1,0.000000,0.121569,0.682353,0.001194,-1,0.065651,-1,...,-29.45260,-1,115.7110,113.7820,77.1652,0,30,0,0,NaN
3520,3521,1,1,0.266667,0.737255,0.968627,0.000193,-1,0.031706,-1,...,-289.99500,-1,103.7200,68.3142,23.7276,0,30,0,0,NaN
3521,3522,1,1,0.800000,0.050980,0.905882,0.000508,-1,0.045225,-1,...,-165.52800,-1,149.4630,84.4952,37.5358,0,30,0,0,NaN
3522,3523,1,1,0.454902,0.956863,0.596078,0.000150,-1,0.024342,-1,...,-7.88496,-1,66.7547,59.5607,22.5162,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.752941,0.937255,0.709804,0.016060,-1,0.418727,-1,...,-284.7210,-1,132.2120,111.4360,77.3042,4662,2088,0,0,NaN
1,2,1,0,0.301961,0.113725,0.980392,0.024167,-1,0.585923,-1,...,-302.1880,-1,187.3730,152.7340,91.5863,2541,331,0,0,NaN
2,3,1,0,0.254902,0.843137,0.890196,0.022209,-1,0.552684,-1,...,-244.4870,-1,187.5780,142.4190,96.9818,1864,754,0,0,NaN
3,4,1,0,0.192157,0.458824,0.643137,0.026737,-1,0.583203,-1,...,-228.8700,-1,188.9170,163.1510,123.3590,1179,317,0,0,NaN
4,5,1,0,0.168627,0.345098,0.058824,0.021244,-1,0.471948,-1,...,-282.7440,-1,183.7270,177.5570,110.2870,1133,70,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1405,1406,1,1,0.854902,0.698039,0.650980,0.000583,-1,0.044436,-1,...,-205.0350,-1,105.6790,97.0723,47.6090,0,30,0,0,NaN
1406,1407,1,1,0.380392,0.039216,0.458824,0.000211,-1,0.034124,-1,...,250.9570,-1,134.1600,84.8358,20.5895,0,30,0,0,NaN
1407,1408,1,1,0.286275,0.960784,0.058824,0.000467,-1,0.042897,-1,...,-89.7286,-1,99.2597,85.7588,37.1219,0,30,0,0,NaN
1408,1409,1,1,0.470588,0.568627,0.050980,0.000985,-1,0.057229,-1,...,-285.4860,-1,119.6890,102.8790,63.3423,6,30,0,0,NaN
1409,1410,1,1,0.329412,0.364706,0.070588,0.000600,-1,0.045376,-1,...,124.8270,-1,112.7720,105.9200,42.9146,0,27,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.027451,0.800000,0.443137,0.001397,-1,0.070121,-1,...,20.9154,-1,58.8898,50.1839,32.0123,5001,8,0,0,NaN
1,2,1,0,0.007843,0.411765,0.564706,0.002420,-1,0.106698,-1,...,-67.1191,-1,62.9045,51.8344,39.0357,4999,340,0,0,NaN
2,3,1,0,0.745098,0.909804,0.086275,0.004936,-1,0.194971,-1,...,-172.5580,-1,99.8505,72.4508,41.5841,4899,1943,0,0,NaN
3,4,1,0,0.164706,0.380392,0.149020,0.004966,-1,0.183299,-1,...,-335.1310,-1,91.9170,86.6821,42.6603,4269,330,0,0,NaN
4,5,1,0,0.627451,0.274510,0.431373,0.015462,-1,0.390992,-1,...,-327.3480,-1,145.3170,115.3150,75.9362,2241,9,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1628,1629,1,1,0.529412,0.635294,0.666667,0.000302,-1,0.035321,-1,...,-357.5340,-1,110.7600,59.6840,32.4452,0,30,0,0,NaN
1629,1630,1,1,0.015686,0.780392,0.905882,0.000525,-1,0.046030,-1,...,641.0880,-1,120.8720,80.0762,51.4570,0,30,0,0,NaN
1630,1631,1,1,0.411765,0.364706,0.435294,0.000523,-1,0.042633,-1,...,-60.8928,-1,129.7110,75.1392,46.5927,0,30,0,0,NaN
1631,1632,1,1,0.682353,0.003922,0.662745,0.000484,-1,0.043140,-1,...,555.0530,-1,144.0410,83.5287,41.4071,0,30,0,0,NaN
1632,1633,1,1,0.501961,0.215686,0.588235,0.000404,-1,0.039022,-1,...,-220.2510,-1,130.0860,83.9598,36.8134,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.517647,0.647059,0.478431,0.015994,-1,0.495209,-1,...,-293.413,-1,225.6850,114.7130,75.5899,2112,205,0,0,NaN
1,2,1,0,0.090196,0.392157,0.447059,0.018802,-1,0.507707,-1,...,-276.576,-1,210.7180,139.0950,81.7783,1490,120,0,0,NaN
2,3,1,0,0.937255,0.101961,0.941176,0.011584,-1,0.406632,-1,...,478.864,-1,354.9280,119.6480,80.1398,471,1,0,0,NaN
3,4,1,0,0.749020,0.901961,0.435294,0.009315,-1,0.298773,-1,...,601.372,-1,228.7870,118.9800,70.1819,370,0,0,0,NaN
4,5,1,0,0.266667,0.913725,0.035294,0.005944,-1,0.209984,-1,...,-358.171,-1,152.8550,105.4480,57.7618,344,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3190,3191,1,1,0.984314,0.752941,0.529412,0.000269,-1,0.030055,-1,...,454.873,-1,97.1151,65.5531,27.5274,0,30,0,0,NaN
3191,3192,1,1,0.776471,0.278431,0.450980,0.000888,-1,0.051557,-1,...,-258.514,-1,117.3890,109.3330,72.0651,0,30,0,0,NaN
3192,3193,1,1,0.976471,0.819608,0.458824,0.000174,-1,0.025097,-1,...,324.976,-1,92.2714,64.6761,33.1848,0,30,0,0,NaN
3193,3194,1,1,0.419608,0.588235,0.988235,0.000654,-1,0.045638,-1,...,-322.814,-1,109.8650,94.0882,52.6453,1,30,0,0,NaN
3194,3195,1,1,0.588235,0.823529,0.058824,0.000770,-1,0.053032,-1,...,-348.093,-1,111.9300,110.4690,45.0211,2,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.745098,0.050980,0.501961,0.015712,-1,0.503705,-1,...,-69.7623,-1,250.6070,128.8580,55.0561,4787,593,0,0,NaN
1,2,1,0,0.584314,0.074510,0.403922,0.027322,-1,0.575213,-1,...,-200.8820,-1,172.1180,138.3310,85.9490,3952,111,0,0,NaN
2,3,1,0,0.356863,0.737255,0.196078,0.016243,-1,0.492421,-1,...,-245.0850,-1,163.1700,109.5030,62.3010,3906,1791,0,0,NaN
3,4,1,0,0.419608,0.149020,1.000000,0.025359,-1,0.655148,-1,...,393.6200,-1,470.3570,124.8770,86.5065,2529,57,0,0,NaN
4,5,1,0,0.364706,0.768627,0.921569,0.022419,-1,0.576333,-1,...,-487.6740,-1,298.1010,131.3700,78.6329,1596,50,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1967,1968,1,1,0.372549,0.909804,0.498039,0.000170,-1,0.022417,-1,...,264.5800,-1,135.4820,45.7645,28.8685,0,30,0,0,NaN
1968,1969,1,1,0.827451,0.341176,0.403922,0.000285,-1,0.036276,-1,...,111.4900,-1,120.6080,66.3054,41.8430,0,30,0,0,NaN
1969,1970,1,1,0.145098,0.247059,0.815686,0.000103,-1,0.015652,-1,...,408.4590,-1,93.7667,35.8519,24.2510,0,30,0,0,NaN
1970,1971,1,1,0.415686,0.384314,0.172549,0.000485,-1,0.041692,-1,...,-147.5970,-1,87.3771,81.0835,51.6288,0,30,0,0,NaN
1971,1972,1,1,0.223529,0.094118,0.282353,0.000423,-1,0.038773,-1,...,596.3710,-1,121.4430,101.3610,39.0818,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.372549,0.694118,0.898039,0.002922,-1,0.131260,-1,...,-253.597,-1,98.6669,61.4000,40.6277,4940,841,0,0,NaN
1,2,1,0,0.788235,0.913725,0.482353,0.003152,-1,0.140747,-1,...,45.251,-1,107.0050,60.9077,33.5786,4939,264,0,0,NaN
2,3,1,0,0.474510,0.301961,0.470588,0.016033,-1,0.479868,-1,...,-175.265,-1,209.3870,115.6850,66.5826,4902,943,0,0,NaN
3,4,1,0,0.650980,0.541176,0.215686,0.006623,-1,0.263875,-1,...,-355.021,-1,176.8410,73.3608,50.2685,4777,556,0,0,NaN
4,5,1,0,0.423529,0.349020,0.243137,0.028847,-1,0.858625,-1,...,-311.202,-1,490.4740,105.2730,64.2173,4759,2090,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1951,1952,1,1,0.011765,0.815686,0.454902,0.000254,-1,0.030151,-1,...,-474.850,-1,107.3310,80.5989,34.9661,0,30,0,0,NaN
1952,1953,1,1,0.176471,0.525490,1.000000,0.000355,-1,0.035473,-1,...,-115.937,-1,80.9133,75.2723,48.3542,0,30,0,0,NaN
1953,1954,1,1,0.717647,0.129412,0.027451,0.000758,-1,0.051575,-1,...,624.144,-1,120.9720,91.6044,58.1503,0,30,0,0,NaN
1954,1955,1,1,0.898039,0.780392,0.588235,0.000241,-1,0.026656,-1,...,168.494,-1,83.6798,65.2298,38.3271,0,30,0,0,NaN
1955,1956,1,1,0.113725,0.980392,0.207843,0.000738,-1,0.051323,-1,...,-151.868,-1,89.7787,89.0904,54.1319,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.792157,0.537255,0.639216,0.005661,-1,0.214953,-1,...,-95.0327,-1,90.6993,77.5322,49.8921,4965,1346,0,0,NaN
1,2,1,0,0.270588,0.741176,0.549020,0.011499,-1,0.429401,-1,...,-246.9750,-1,181.4310,80.8901,54.6699,4765,3523,0,0,NaN
2,3,1,0,0.070588,0.321569,0.670588,0.003177,-1,0.159706,-1,...,-202.9500,-1,109.5960,68.4690,33.2971,4443,1081,0,0,NaN
3,4,1,0,0.145098,0.137255,1.000000,0.025472,-1,0.568584,-1,...,-296.8100,-1,148.5630,140.7020,78.9919,3518,1524,0,0,NaN
4,5,1,0,0.243137,0.898039,0.470588,0.012937,-1,0.455712,-1,...,117.7670,-1,191.9810,106.9050,67.8911,1321,3,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3598,3599,1,1,0.231373,0.474510,0.780392,0.000814,-1,0.052651,-1,...,-295.1960,-1,108.5590,96.2712,58.0878,0,30,0,0,NaN
3599,3600,1,1,0.556863,0.717647,0.537255,0.000438,-1,0.043765,-1,...,11.9780,-1,107.9760,73.8937,42.9639,1,30,0,0,NaN
3600,3601,1,1,0.545098,0.956863,0.380392,0.000767,-1,0.049139,-1,...,-262.4900,-1,110.4830,92.1086,74.3584,1,30,0,0,NaN
3601,3602,1,1,0.290196,0.149020,0.505882,0.000394,-1,0.037299,-1,...,-326.8060,-1,111.7560,80.6968,40.2810,0,30,0,0,NaN
3602,3603,1,1,0.282353,0.490196,0.113725,0.000338,-1,0.034362,-1,...,-238.3780,-1,112.1180,74.6646,45.0857,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.172549,0.631373,0.674510,0.002002,-1,0.101638,-1,...,16.09330,-1,58.2082,55.6839,34.9454,5000,2375,0,0,NaN
1,2,1,0,0.835294,0.882353,0.521569,0.028517,-1,0.668616,-1,...,-205.83200,-1,259.0570,148.4150,94.2334,1286,26,0,0,NaN
2,3,1,0,0.878431,0.380392,0.215686,0.005081,-1,0.224311,-1,...,2.05058,-1,195.7530,93.0206,64.1959,440,0,0,0,NaN
3,4,1,0,0.498039,0.792157,0.184314,0.004627,-1,0.191859,-1,...,-282.59400,-1,141.3370,97.4330,59.1086,428,1,0,0,NaN
4,5,1,0,0.576471,0.811765,0.462745,0.004165,-1,0.217164,-1,...,-363.18000,-1,213.6030,86.4467,49.7138,388,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017,2018,1,1,0.505882,0.549020,0.647059,0.000783,-1,0.055513,-1,...,-306.19000,-1,115.4140,100.1790,59.1199,0,30,0,0,NaN
2018,2019,1,1,0.705882,0.823529,0.917647,0.000076,-1,0.013572,-1,...,298.83500,-1,70.8490,39.6014,22.0962,0,30,0,0,NaN
2019,2020,1,1,0.603922,0.372549,0.325490,0.000322,-1,0.034281,-1,...,420.67000,-1,117.5410,59.4540,38.3668,0,30,0,0,NaN
2020,2021,1,1,0.945098,0.007843,0.784314,0.000177,-1,0.023108,-1,...,-667.26500,-1,135.7520,48.0052,29.9756,0,30,0,0,NaN
2021,2022,1,1,0.200000,0.619608,0.352941,0.000249,-1,0.025599,-1,...,56.27410,-1,115.6870,56.6499,35.4299,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.376471,0.627451,0.231373,0.005395,-1,0.216546,-1,...,13.1868,-1,104.4540,77.4008,45.4776,1119,0,0,0,NaN
1,2,1,0,0.564706,0.372549,0.454902,0.011583,-1,0.390529,-1,...,-51.0006,-1,207.0420,109.6870,71.5993,993,1,0,0,NaN
2,3,1,0,0.125490,0.360784,0.890196,0.002991,-1,0.166080,-1,...,-64.7138,-1,126.7300,76.9688,43.6024,471,1,0,0,NaN
3,4,1,0,0.670588,0.945098,0.117647,0.003352,-1,0.177880,-1,...,-280.8100,-1,144.9600,77.0815,43.1098,442,0,0,0,NaN
4,5,1,0,0.223529,0.588235,0.588235,0.012646,-1,0.444137,-1,...,-399.9380,-1,231.4540,193.8400,79.3253,441,11,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4291,4292,1,1,0.505882,0.403922,0.850980,0.000142,-1,0.024860,-1,...,-214.2640,-1,97.7747,54.5322,28.5639,0,30,0,0,NaN
4292,4293,1,1,0.643137,0.494118,0.011765,0.000056,-1,0.012925,-1,...,-290.9220,-1,103.0190,39.2755,18.6354,0,30,0,0,NaN
4293,4294,1,1,0.031372,0.270588,0.815686,0.000432,-1,0.035237,-1,...,56.2757,-1,141.2640,65.7640,41.5969,0,30,0,0,NaN
4294,4295,1,1,0.541176,0.713725,0.458824,0.000587,-1,0.054244,-1,...,-287.9650,-1,125.6690,91.8087,45.3700,4,30,0,0,NaN
4295,4296,1,1,0.392157,0.925490,0.368627,0.000429,-1,0.041620,-1,...,-380.7350,-1,115.0220,77.1889,50.4196,3,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.313725,0.231373,0.815686,0.011906,-1,0.364254,-1,...,-293.8710,-1,127.2410,92.4737,58.4241,1700,6,0,0,NaN
1,2,1,0,0.776471,0.831373,0.556863,0.008531,-1,0.300188,-1,...,-130.2160,-1,155.4390,101.6320,57.5474,665,3,0,0,NaN
2,3,1,0,0.431373,0.705882,0.600000,0.008010,-1,0.264562,-1,...,-318.3640,-1,135.3180,117.3450,60.6899,557,0,0,0,NaN
3,4,1,0,0.776471,0.443137,0.600000,0.023524,-1,0.511457,-1,...,-275.3510,-1,221.5120,210.6490,130.9580,474,72,0,0,NaN
4,5,1,0,0.619608,0.478431,0.098039,0.003848,-1,0.186587,-1,...,-326.6930,-1,146.0830,88.8603,56.6347,399,3,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6239,6240,1,1,0.192157,0.729412,0.133333,0.000080,-1,0.015823,-1,...,-353.2270,-1,89.0984,36.1921,19.4968,0,30,0,0,NaN
6240,6241,1,1,0.301961,0.996078,0.615686,0.000754,-1,0.051540,-1,...,-272.5460,-1,100.6520,98.9872,51.7610,0,30,0,0,NaN
6241,6242,1,1,0.905882,0.976471,0.623529,0.000635,-1,0.045006,-1,...,70.7711,-1,86.3340,84.9702,49.8892,0,30,0,0,NaN
6242,6243,1,1,0.211765,0.658824,0.917647,0.000433,-1,0.039345,-1,...,-327.0390,-1,96.5939,85.3531,45.2825,2,30,0,0,NaN
6243,6244,1,1,0.776471,0.580392,0.486275,0.000492,-1,0.042254,-1,...,-310.5760,-1,127.3330,119.9680,80.2233,0,11,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.988235,0.921569,0.580392,0.007423,-1,0.251989,-1,...,-235.4870,-1,93.8794,82.4125,54.6699,4965,1733,0,0,NaN
1,2,1,0,0.121569,0.745098,0.686275,0.005579,-1,0.253139,-1,...,73.8928,-1,117.1130,100.4220,33.3463,4960,840,0,0,NaN
2,3,1,0,0.772549,0.082353,0.811765,0.049641,-1,0.997820,-1,...,-136.7470,-1,291.8700,161.1420,101.6620,4512,1196,0,0,NaN
3,4,1,0,0.003922,0.552941,0.384314,0.007114,-1,0.283046,-1,...,-541.1710,-1,229.9350,74.8575,38.6953,3299,0,0,0,NaN
4,5,1,0,0.015686,0.482353,0.701961,0.017910,-1,0.465738,-1,...,-273.2250,-1,151.0880,139.1760,85.3871,1700,167,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1920,1921,1,1,0.274510,0.682353,0.478431,0.000349,-1,0.046103,-1,...,528.8570,-1,123.0780,71.2929,38.3841,0,30,0,0,NaN
1921,1922,1,1,0.168627,0.639216,0.298039,0.000064,-1,0.011693,-1,...,253.6260,-1,79.7731,36.3984,16.3686,0,30,0,0,NaN
1922,1923,1,1,0.831373,0.807843,0.823529,0.000114,-1,0.017506,-1,...,-157.3630,-1,75.9105,47.5970,25.1747,0,30,0,0,NaN
1923,1924,1,1,0.776471,0.239216,0.901961,0.000115,-1,0.016072,-1,...,-127.1160,-1,61.5220,46.1002,30.8554,0,30,0,0,NaN
1924,1925,1,1,0.611765,0.243137,0.698039,0.000822,-1,0.057083,-1,...,480.4910,-1,109.7770,100.7900,52.3810,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.623529,0.615686,0.301961,0.026104,-1,0.585814,-1,...,-273.358,-1,152.720,149.2870,80.7226,4239,443,0,0,NaN
1,2,1,0,0.866667,0.741176,0.905882,0.024795,-1,0.564181,-1,...,-256.673,-1,161.204,140.1330,80.8154,3841,535,0,0,NaN
2,3,1,0,0.670588,0.901961,0.258824,0.042384,-1,0.806689,-1,...,-248.658,-1,316.361,220.6740,146.1710,891,114,0,0,NaN
3,4,1,0,0.980392,0.094118,0.000000,0.014307,-1,0.392309,-1,...,-257.848,-1,172.101,162.1590,76.7523,612,0,0,0,NaN
4,5,1,0,0.250980,0.098039,0.615686,0.011935,-1,0.334485,-1,...,-161.667,-1,165.192,164.8480,77.7107,329,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
819,820,1,1,0.827451,0.733333,0.149020,0.000477,-1,0.049120,-1,...,490.489,-1,105.066,83.3844,34.7546,0,30,0,0,NaN
820,821,1,1,0.372549,0.262745,0.364706,0.000402,-1,0.048091,-1,...,-289.986,-1,135.617,93.7207,30.2424,0,30,0,0,NaN
821,822,1,1,0.964706,0.882353,0.435294,0.000351,-1,0.038261,-1,...,-201.327,-1,140.552,72.3596,32.1264,0,30,0,0,NaN
822,823,1,1,0.301961,0.015686,0.929412,0.000560,-1,0.050257,-1,...,-268.905,-1,128.274,99.4044,33.1134,0,30,0,0,NaN
823,824,1,1,0.513725,0.811765,0.243137,0.000582,-1,0.046748,-1,...,-292.625,-1,112.796,87.5555,46.2738,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.905882,0.427451,0.443137,0.006089,-1,0.204119,-1,...,45.5120,-1,111.0490,87.5458,51.4152,4980,2044,0,0,NaN
1,2,1,0,0.956863,0.713725,0.682353,0.005692,-1,0.254791,-1,...,-337.7280,-1,185.8830,107.4110,58.2203,617,0,0,0,NaN
2,3,1,0,0.894118,0.878431,0.427451,0.002399,-1,0.136816,-1,...,141.9070,-1,108.8720,56.0785,37.6451,599,0,0,0,NaN
3,4,1,0,0.921569,0.090196,0.745098,0.002066,-1,0.109919,-1,...,-41.6026,-1,88.9313,60.1560,40.3878,552,0,0,0,NaN
4,5,1,0,0.819608,0.772549,0.745098,0.002499,-1,0.153713,-1,...,391.6470,-1,128.2330,76.8763,39.2083,424,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1758,1759,1,1,0.870588,0.066667,0.619608,0.000364,-1,0.037902,-1,...,-273.0800,-1,77.9645,74.4587,43.7308,0,30,0,0,NaN
1759,1760,1,1,0.129412,0.435294,0.694118,0.000187,-1,0.025226,-1,...,-569.8580,-1,124.7350,47.7750,28.8108,0,30,0,0,NaN
1760,1761,1,1,0.129412,0.000000,0.643137,0.000965,-1,0.057194,-1,...,623.8970,-1,120.6810,109.5380,71.3296,0,30,0,0,NaN
1761,1762,1,1,0.662745,0.423529,0.203922,0.000323,-1,0.033848,-1,...,-347.7030,-1,127.6170,60.9962,36.1464,0,30,0,0,NaN
1762,1763,1,1,0.776471,0.337255,0.764706,0.000067,-1,0.012571,-1,...,317.2640,-1,91.5396,34.2766,18.8265,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.149020,0.423529,0.541176,0.010101,-1,0.372513,-1,...,324.3600,-1,250.1050,72.0480,45.6750,4914,2165,0,0,NaN
1,2,1,0,0.109804,0.250980,0.537255,0.007384,-1,0.255611,-1,...,31.4210,-1,93.2155,86.6303,51.4454,4874,3077,0,0,NaN
2,3,1,0,0.560784,0.490196,0.513725,0.006773,-1,0.250741,-1,...,-236.2770,-1,100.9480,79.7917,54.4450,4778,1153,0,0,NaN
3,4,1,0,0.176471,0.498039,0.584314,0.011327,-1,0.314740,-1,...,-263.2200,-1,108.9060,103.4710,68.3482,3818,1715,0,0,NaN
4,5,1,0,0.062745,0.890196,0.203922,0.034359,-1,0.987556,-1,...,-233.5440,-1,371.2070,136.1870,75.5744,3568,1248,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1889,1890,1,1,0.533333,0.556863,0.403922,0.000939,-1,0.055379,-1,...,24.0392,-1,108.7110,95.5477,59.7065,0,30,0,0,NaN
1890,1891,1,1,0.360784,0.725490,0.011765,0.000194,-1,0.026895,-1,...,-393.3580,-1,107.9060,59.4205,30.3433,0,30,0,0,NaN
1891,1892,1,1,0.901961,0.462745,0.407843,0.000374,-1,0.035801,-1,...,373.8540,-1,150.1880,62.5348,37.5026,1,30,0,0,NaN
1892,1893,1,1,0.207843,0.607843,0.611765,0.000200,-1,0.029259,-1,...,476.3840,-1,130.7220,57.0982,25.6870,0,30,0,0,NaN
1893,1894,1,1,0.129412,0.984314,0.349020,0.000250,-1,0.023506,-1,...,-91.6498,-1,67.8342,62.6459,37.3715,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.815686,0.341176,0.313725,0.009091,-1,0.301803,-1,...,-118.8390,-1,88.1230,85.1728,59.5502,4923,1490,0,0,NaN
1,2,1,0,0.403922,0.317647,0.984314,0.032637,-1,0.743880,-1,...,-97.6569,-1,195.0650,162.2430,94.6963,4763,1367,0,0,NaN
2,3,1,0,0.141176,0.254902,0.058824,0.049324,-1,1.031550,-1,...,-94.6718,-1,240.4830,177.1570,106.7840,4704,724,0,0,NaN
3,4,1,0,0.270588,0.701961,0.345098,0.009156,-1,0.342915,-1,...,-376.6010,-1,240.6510,85.8748,52.2283,4430,783,0,0,NaN
4,5,1,0,0.827451,0.266667,0.380392,0.017777,-1,0.497582,-1,...,-239.6040,-1,192.1540,118.5250,80.0751,1497,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4718,4719,1,1,0.760784,0.847059,0.113725,0.000186,-1,0.026033,-1,...,-360.4640,-1,142.5630,48.8939,27.1994,0,30,0,0,NaN
4719,4720,1,1,0.070588,0.407843,0.007843,0.000074,-1,0.012923,-1,...,-252.7660,-1,107.0360,44.6952,18.3388,0,30,0,0,NaN
4720,4721,1,1,0.933333,0.015686,0.513725,0.000164,-1,0.019680,-1,...,200.0790,-1,83.8238,48.8259,33.0124,0,30,0,0,NaN
4721,4722,1,1,0.674510,0.650980,0.345098,0.000568,-1,0.045193,-1,...,-327.3070,-1,119.5970,83.5267,51.8694,3,30,0,0,NaN
4722,4723,1,1,0.145098,0.341176,0.188235,0.000109,-1,0.017066,-1,...,-372.4500,-1,85.0549,42.8988,25.3766,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.654902,0.070588,0.458824,0.001973,-1,0.095652,-1,...,-139.330,-1,69.9734,65.0262,38.5145,4994,2717,0,0,NaN
1,2,1,0,0.878431,0.952941,0.262745,0.003210,-1,0.133886,-1,...,-102.531,-1,88.6923,75.5660,42.2487,4973,3537,0,0,NaN
2,3,1,0,0.388235,0.431373,0.858824,0.023074,-1,0.566661,-1,...,-252.510,-1,134.1800,117.5450,77.9872,3971,3007,0,0,NaN
3,4,1,0,0.439216,0.168627,0.725490,0.042186,-1,0.916836,-1,...,255.056,-1,455.0210,148.3710,84.1695,3784,521,0,0,NaN
4,5,1,0,0.090196,0.525490,0.803922,0.046863,-1,0.906883,-1,...,-203.748,-1,328.7150,203.2950,127.1890,1366,63,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1547,1548,1,1,0.345098,0.376471,0.568627,0.000308,-1,0.025899,-1,...,-180.125,-1,72.5802,67.9985,37.9577,0,30,0,0,NaN
1548,1549,1,1,0.152941,0.858824,0.164706,0.000688,-1,0.049842,-1,...,534.329,-1,128.3120,88.7501,51.8699,0,30,0,0,NaN
1549,1550,1,1,1.000000,0.839216,0.945098,0.000322,-1,0.036416,-1,...,-258.413,-1,131.3580,81.0721,39.2639,0,30,0,0,NaN
1550,1551,1,1,0.643137,0.478431,0.345098,0.000317,-1,0.029171,-1,...,-244.071,-1,73.9114,71.0585,38.0513,0,30,0,0,NaN
1551,1552,1,1,0.513725,0.423529,0.968627,0.000305,-1,0.029864,-1,...,-684.272,-1,120.2380,69.1695,36.4053,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.988235,0.019608,0.113725,0.075605,-1,1.503720,-1,...,-15.6256,-1,353.1060,334.1010,209.7420,2770,17,0,0,NaN
1,2,1,0,0.517647,0.772549,0.427451,0.034625,-1,0.676581,-1,...,-188.7700,-1,229.7520,179.1610,108.2630,1448,117,0,0,NaN
2,3,1,0,0.898039,0.988235,0.752941,0.011801,-1,0.404008,-1,...,85.9714,-1,202.6920,127.8040,79.2246,760,0,0,0,NaN
3,4,1,0,0.152941,0.352941,0.282353,0.008069,-1,0.317311,-1,...,-295.7490,-1,195.7080,116.2620,77.2066,702,0,0,0,NaN
4,5,1,0,0.674510,0.090196,0.098039,0.011100,-1,0.455039,-1,...,-63.5216,-1,254.0410,179.2030,81.6392,518,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4764,4765,1,1,0.662745,0.427451,0.082353,0.000208,-1,0.026110,-1,...,267.7730,-1,141.3780,52.1922,33.5639,0,30,0,0,NaN
4765,4766,1,1,0.411765,0.419608,0.772549,0.000339,-1,0.030755,-1,...,-121.2550,-1,105.7950,73.1743,38.4295,0,30,0,0,NaN
4766,4767,1,1,0.800000,0.862745,0.768627,0.000176,-1,0.022569,-1,...,-203.1790,-1,78.9930,51.3630,31.9031,0,30,0,0,NaN
4767,4768,1,1,0.027451,0.611765,0.298039,0.000225,-1,0.024365,-1,...,645.6290,-1,80.4028,58.0094,32.2691,0,30,0,0,NaN
4768,4769,1,1,0.337255,0.019608,0.623529,0.000583,-1,0.039819,-1,...,-207.6170,-1,109.1460,89.9087,60.6070,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.611765,0.368627,0.917647,0.006886,-1,0.253532,-1,...,-356.7950,-1,109.7370,100.5100,47.7300,934,0,0,0,NaN
1,2,1,0,0.819608,0.458824,0.933333,0.008051,-1,0.294944,-1,...,-356.6760,-1,148.0640,129.3130,55.8360,659,0,0,0,NaN
2,3,1,0,0.356863,0.682353,0.925490,0.017085,-1,0.544190,-1,...,278.9170,-1,464.5010,164.7220,81.0027,452,1,0,0,NaN
3,4,1,0,0.019608,0.098039,0.450980,0.001820,-1,0.094991,-1,...,-253.0670,-1,92.5453,65.7799,42.0371,336,0,0,0,NaN
4,5,1,0,0.031372,1.000000,0.819608,0.002585,-1,0.150584,-1,...,369.6420,-1,222.8270,69.8348,43.3760,298,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2036,2037,1,1,0.533333,0.996078,0.250980,0.000593,-1,0.042361,-1,...,-303.8330,-1,123.9250,86.2460,59.2093,2,30,0,0,NaN
2037,2038,1,1,0.964706,0.690196,0.682353,0.000464,-1,0.039599,-1,...,-47.9563,-1,77.8904,75.2411,41.0357,0,30,0,0,NaN
2038,2039,1,1,0.156863,0.737255,0.674510,0.000291,-1,0.029457,-1,...,-340.8770,-1,138.4840,57.3813,38.7137,4,30,0,0,NaN
2039,2040,1,1,0.756863,0.396078,0.482353,0.000415,-1,0.034534,-1,...,-341.0840,-1,100.0650,75.7319,45.6301,0,30,0,0,NaN
2040,2041,1,1,0.317647,0.623529,0.988235,0.000179,-1,0.023181,-1,...,15.2494,-1,82.1158,53.5195,28.5023,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.698039,0.843137,0.321569,0.044982,-1,0.879467,-1,...,-31.70360,-1,188.3710,180.6520,110.8130,4545,1228,0,0,NaN
1,2,1,0,0.372549,0.639216,0.082353,0.006591,-1,0.285708,-1,...,301.67700,-1,191.8830,82.1283,47.7085,844,0,0,0,NaN
2,3,1,0,0.250980,0.882353,0.968627,0.011092,-1,0.389337,-1,...,-367.18100,-1,244.4940,112.9240,78.9348,505,0,0,0,NaN
3,4,1,0,0.917647,0.549020,0.074510,0.014531,-1,0.434678,-1,...,9.55634,-1,221.1910,154.6970,87.5756,466,1,0,0,NaN
4,5,1,0,0.658824,0.403922,0.192157,0.011159,-1,0.330429,-1,...,-164.33800,-1,158.6260,127.5350,73.9535,438,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3819,3820,1,1,0.098039,0.741176,0.780392,0.000659,-1,0.047567,-1,...,-303.13700,-1,126.5650,87.0158,47.6969,1,30,0,0,NaN
3820,3821,1,1,0.749020,0.674510,0.925490,0.000216,-1,0.034526,-1,...,293.01200,-1,99.1274,79.2701,20.7740,0,30,0,0,NaN
3821,3822,1,1,0.619608,0.682353,0.156863,0.000071,-1,0.019341,-1,...,-358.36800,-1,125.0420,49.5415,17.5889,2,30,0,0,NaN
3822,3823,1,1,0.156863,0.552941,0.478431,0.000370,-1,0.033475,-1,...,-50.59510,-1,83.8123,75.6272,43.6325,0,30,0,0,NaN
3823,3824,1,1,0.274510,0.619608,0.388235,0.000263,-1,0.029074,-1,...,675.79400,-1,101.0110,84.1732,33.9427,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.729412,0.854902,0.313725,0.052971,-1,1.371290,-1,...,-220.4380,-1,741.1400,131.0220,81.7255,5205,1735,0,0,NaN
1,2,1,0,0.266667,0.211765,0.796078,0.032706,-1,0.964016,-1,...,-98.2887,-1,307.3530,145.6510,62.4110,5073,1777,0,0,NaN
2,3,1,0,0.329412,0.301961,0.882353,0.007660,-1,0.290699,-1,...,581.6130,-1,240.1790,71.6784,45.3901,4940,207,0,0,NaN
3,4,1,0,0.552941,0.592157,0.780392,0.008517,-1,0.251620,-1,...,-243.9260,-1,108.5660,92.7825,73.6296,4931,1737,0,0,NaN
4,5,1,0,0.803922,0.427451,0.945098,0.002316,-1,0.109384,-1,...,-270.5320,-1,63.8078,54.5105,35.1589,4914,693,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2799,2800,1,1,0.239216,0.756863,0.431373,0.000140,-1,0.020576,-1,...,-24.6070,-1,81.7434,50.9677,27.0694,0,30,0,0,NaN
2800,2801,1,1,0.631373,0.525490,0.168627,0.000266,-1,0.032288,-1,...,289.2790,-1,128.9110,64.3607,38.1495,0,30,0,0,NaN
2801,2802,1,1,0.874510,0.341176,0.662745,0.000249,-1,0.028310,-1,...,107.2400,-1,101.8100,57.4039,32.6796,0,30,0,0,NaN
2802,2803,1,1,0.584314,0.345098,0.756863,0.000321,-1,0.034173,-1,...,-337.7670,-1,117.4120,59.8915,37.1682,0,30,0,0,NaN
2803,2804,1,1,0.592157,0.792157,0.498039,0.000507,-1,0.040827,-1,...,207.2020,-1,103.1830,72.8877,47.0851,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.274510,0.615686,0.988235,0.010750,-1,0.320033,-1,...,-274.4600,-1,94.0439,92.8566,46.6482,4874,3331,0,0,NaN
1,2,1,0,0.505882,0.552941,0.678431,0.007467,-1,0.238479,-1,...,686.9680,-1,117.5670,104.7970,55.1938,3469,1962,0,0,NaN
2,3,1,0,0.368627,0.058824,0.141176,0.036922,-1,0.702128,-1,...,-263.0110,-1,172.5780,153.4760,111.2910,2973,52,0,0,NaN
3,4,1,0,0.101961,0.596078,0.650980,0.036555,-1,0.816172,-1,...,395.8670,-1,499.7420,163.2560,100.9200,1342,122,0,0,NaN
4,5,1,0,0.647059,0.470588,0.780392,0.018920,-1,0.443035,-1,...,-249.2460,-1,205.1320,177.3920,139.1850,411,29,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1443,1444,1,1,0.207843,0.996078,0.792157,0.000319,-1,0.032246,-1,...,75.4846,-1,97.0973,76.2894,31.8820,0,30,0,0,NaN
1444,1445,1,1,0.266667,0.498039,0.815686,0.000339,-1,0.037004,-1,...,-294.3850,-1,112.5720,76.9916,31.5107,0,30,0,0,NaN
1445,1446,1,1,0.788235,0.768627,0.945098,0.000310,-1,0.042226,-1,...,-329.2850,-1,103.4820,84.3766,25.3772,0,30,0,0,NaN
1446,1447,1,1,0.466667,0.313725,0.082353,0.000415,-1,0.038768,-1,...,-271.7880,-1,101.5320,92.7079,33.4565,1,30,0,0,NaN
1447,1448,1,1,0.364706,0.858824,0.427451,0.000850,-1,0.054035,-1,...,-232.5780,-1,142.8570,84.9293,57.7337,0,30,0,0,NaN

,id,visible,probe,colorR,colorG,colorB,volumeAlpha,volumeIso,surfaceAreaAlpha,surfaceAreaIso,...,centroidZ,distance,PCA1,PCA2,PCA3,probeParticleCountAlpha1,probeParticleCountAlpha2,probeParticleCountIso1,probeParticleCountIso2,notes
0,1,1,0,0.400000,0.745098,0.807843,0.006370,-1,0.221951,-1,...,-132.26000,-1,86.1971,80.7532,53.1744,4977,791,0,0,NaN
1,2,1,0,0.776471,0.635294,0.000000,0.001390,-1,0.084001,-1,...,165.92300,-1,93.4047,46.0009,26.3587,4310,2,0,0,NaN
2,3,1,0,0.321569,0.717647,0.823529,0.020777,-1,0.588905,-1,...,197.89400,-1,299.7830,117.8750,71.8054,2477,171,0,0,NaN
3,4,1,0,0.694118,0.964706,0.733333,0.023280,-1,0.608266,-1,...,120.25800,-1,226.1600,166.5140,94.4906,1188,70,0,0,NaN
4,5,1,0,0.945098,0.670588,0.490196,0.008134,-1,0.276730,-1,...,115.29500,-1,203.8110,108.4400,71.5172,525,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3046,3047,1,1,0.258824,0.780392,0.200000,0.000143,-1,0.018669,-1,...,-6.16851,-1,80.7946,50.7776,35.1112,0,30,0,0,NaN
3047,3048,1,1,0.250980,0.921569,0.654902,0.000202,-1,0.024656,-1,...,536.94500,-1,132.2360,54.0821,30.9641,0,30,0,0,NaN
3048,3049,1,1,0.568627,0.674510,0.176471,0.000582,-1,0.048721,-1,...,-459.80700,-1,117.0480,91.9859,42.0999,0,30,0,0,NaN
3049,3050,1,1,0.572549,0.000000,0.145098,0.000058,-1,0.013085,-1,...,-353.22200,-1,103.8230,33.4171,15.9351,0,30,0,0,NaN
3050,3051,1,1,0.094118,0.898039,0.827451,0.000167,-1,0.019874,-1,...,-131.52000,-1,83.1850,52.6038,35.9771,0,30,0,0,NaN

In [68]:
from pandas.core import describe
for dataset in dataframes_list:
    datasets.drop([' visible', ' colorR', ' colorG', ' colorB', 'notes'], axis='columns', inplace=True)

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None

None